/**
 * Describes every editable section of the app for the admin panel.
 * The admin panel renders its forms from this file, so adding a field here
 * (and reading it in the app) is all it takes to make something editable.
 *
 * Field types:
 *  text, textarea, number, boolean, color, image, images, link, icon,
 *  select (options), datetime, product, products, category, colors, video,
 *  list (of `fields`), group (of `fields`), strings (list of short texts)
 */

const LINK_HELP = 'A product (/products/handle), a collection (/collections/ghee), an app screen (app:/coins) or any https:// link.';
const ICON_HELP = 'Any Material Design icon name, e.g. gift-outline. Browse them at pictogrammers.com/library/mdi';

const schedule = [
  { key: 'startAt', type: 'datetime', label: 'Show from', help: 'Leave empty to show right away.' },
  { key: 'endAt', type: 'datetime', label: 'Show until', help: 'Leave empty to keep showing.' },
];

const AUDIENCES = [
  { value: 'all', label: 'Everyone with the app' },
  { value: 'members', label: 'Members only' },
  { value: 'non_members', label: 'Everyone except members' },
  { value: 'logged_in', label: 'Logged-in customers' },
  { value: 'guests', label: 'People not logged in' },
];

const faq = (label = 'Questions') => ({
  key: 'faq',
  type: 'list',
  label,
  itemLabel: '{q}',
  fields: [
    { key: 'q', type: 'text', label: 'Question' },
    { key: 'a', type: 'textarea', label: 'Answer', help: 'You can use {per100}, {pendingDays}, {welcomeBonus}.' },
  ],
});

const SECTION_TYPES = [
  { value: 'categories', label: 'Category icons' },
  { value: 'deals', label: 'Deals row (biggest discounts)' },
  { value: 'benefits', label: 'Benefits Club banner' },
  { value: 'grid', label: 'Product grid' },
  { value: 'row', label: 'Product row (scrolls sideways)' },
  { value: 'promo', label: 'Promo strip (image + text)' },
  { value: 'image', label: 'Full-width image banner' },
  { value: 'reviews', label: 'Customer reviews' },
  { value: 'pillars', label: 'Rosier experience (4 pillars)' },
];

export const SCHEMA = [
  {
    key: 'onboarding',
    title: 'Intro slides',
    icon: 'presentation-play',
    description: 'The slides people see the first time they open the app. Raise "Show again version" to show them to everyone once more.',
    fields: [
      { key: 'reshowVersion', type: 'number', label: 'Show again version', help: 'Increase by 1 and publish: every user sees the intro slides again on their next app open.' },
      { key: 'vibrant', type: 'boolean', label: 'Colourful animated background (glowing colours, sparkles, 3D swipe, confetti at the end)', help: 'Off = the plain background colour below.' },
      {
        key: 'swipeStyle',
        type: 'select',
        label: 'Swipe animation (how pictures move between slides)',
        options: [
          { value: '3d', label: '3D turn (default)' },
          { value: 'cube', label: 'Cube rotate' },
          { value: 'zoom', label: 'Zoom in / out' },
          { value: 'stack', label: 'Card stack' },
          { value: 'fade', label: 'Cross-fade' },
          { value: 'flip', label: 'Flip up' },
          { value: 'rise', label: 'Drop & tilt' },
          { value: 'flat', label: 'Simple slide (no effect)' },
        ],
      },
      { key: 'background', type: 'color', label: 'Background colour' },
      { key: 'accent', type: 'color', label: 'Title colour' },
      { key: 'skipLabel', type: 'text', label: 'Skip button text' },
      { key: 'buttonLabel', type: 'text', label: 'Last button text' },
      { key: 'namePlaceholder', type: 'text', label: 'Name box placeholder' },
      { key: 'welcomeNote', type: 'text', label: 'Welcome coins note', help: '{welcomeBonus} becomes the welcome coin amount.' },
      {
        key: 'slides',
        type: 'list',
        label: 'Slides',
        itemLabel: '{title}',
        newItem: { enabled: true, art: 'image', showLogo: false, title: 'NEW SLIDE', sub: '', image: '', images: [], chips: [], showNameInput: false, artHeight: 52, artScale: 1, videoWidth: 62, videoRatio: 1.78, videoRadius: 28, videoFit: 'cover', titleSize: 34, titleColor: '', subSize: 15, subColor: '', colors: [], textFx: 'words', artMotion: 'none', bgFx: 'none' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this slide' },
          { key: 'artHeight', type: 'number', label: 'Picture / video area height (% of screen)', help: 'Default 52. Tip: drag the ↕ handle in the phone preview.' },
          { key: 'artScale', type: 'number', label: 'Picture size (× normal)', help: '1 = normal, 1.2 = bigger, 0.8 = smaller.', showIf: { art: ['collage', 'churn', 'image', 'coins'] } },
          { key: 'videoWidth', type: 'number', label: 'Video width (% of screen)', help: 'Default 62. 100 = edge to edge.', showIf: { art: ['video'] } },
          { key: 'videoRatio', type: 'number', label: 'Video shape (height ÷ width)', help: '1.78 = tall phone video (9:16), 1 = square, 0.56 = wide (16:9).', showIf: { art: ['video'] } },
          { key: 'videoRadius', type: 'number', label: 'Video corner roundness', help: 'Default 28. 0 = sharp.', showIf: { art: ['video'] } },
          {
            key: 'videoFit',
            type: 'select',
            label: 'Video fit',
            options: [
              { value: 'cover', label: 'Fill the frame (may crop edges)' },
              { value: 'contain', label: 'Show the whole video' },
            ],
            showIf: { art: ['video', 'video_full'] },
          },
          { key: 'titleSize', type: 'number', label: 'Title size', help: 'Default 34.' },
          { key: 'titleColor', type: 'color', label: 'Title colour', help: 'Empty = intro title colour.' },
          { key: 'subSize', type: 'number', label: 'Text size', help: 'Default 15.' },
          { key: 'subColor', type: 'color', label: 'Text colour' },
          { key: 'colors', type: 'colors', label: 'Slide colours (colourful background)', help: '1st = background, then up to 3 glow colours. The background flows between slides as people swipe.' },
          {
            key: 'art',
            type: 'select',
            label: 'Animation',
            options: [
              { value: 'collage', label: 'Floating photo collage (up to 7 photos)' },
              { value: 'churn', label: 'Spinning rings around one photo' },
              { value: 'coins', label: 'Falling Rosier coins' },
              { value: 'image', label: 'One big floating image' },
              { value: 'video', label: 'Video in a rounded frame' },
              { value: 'video_full', label: 'Full-screen video behind the text' },
            ],
          },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'sub', type: 'textarea', label: 'Text' },
          { key: 'showLogo', type: 'boolean', label: 'Show Rosier logo above title' },
          {
            key: 'textFx',
            type: 'select',
            label: 'Title animation',
            options: [
              { value: 'words', label: 'Words pop up one by one (default)' },
              { value: 'letters', label: 'Letters drop in one by one' },
              { value: 'typewriter', label: 'Typewriter' },
              { value: 'fade', label: 'Soft fade' },
              { value: 'slideUp', label: 'Slide up' },
              { value: 'slideLeft', label: 'Words slide in from the left' },
              { value: 'zoom', label: 'Words zoom in' },
              { value: 'bounce', label: 'Words bounce in' },
              { value: 'flip', label: 'Words flip in' },
              { value: 'swing', label: 'Words swing in' },
              { value: 'speed', label: 'Words zip in (light speed)' },
              { value: 'spin', label: 'Words spin in' },
              { value: 'none', label: 'No animation' },
            ],
          },
          {
            key: 'artMotion',
            type: 'select',
            label: 'Picture motion (keeps moving)',
            options: [
              { value: 'none', label: 'None (default)' },
              { value: 'float', label: 'Float up and down' },
              { value: 'pulse', label: 'Pulse (heartbeat)' },
              { value: 'breathe', label: 'Breathe (slow grow & glow)' },
              { value: 'swing', label: 'Swing' },
              { value: 'wobble', label: 'Wobble' },
              { value: 'bounce', label: 'Bounce' },
              { value: 'spin', label: 'Slow spin' },
            ],
            showIf: { art: ['collage', 'churn', 'image', 'coins', 'video'] },
          },
          {
            key: 'bgFx',
            type: 'select',
            label: 'Background effect on this slide',
            options: [
              { value: 'none', label: 'None (default)' },
              { value: 'sparkles', label: '✦ Golden sparkles' },
              { value: 'confetti', label: '🎉 Confetti' },
              { value: 'petals', label: '🌸 Flower petals' },
              { value: 'hearts', label: '♥ Hearts' },
              { value: 'snow', label: '❄ Snow' },
              { value: 'diyas', label: '🪔 Rising diyas' },
              { value: 'holi', label: '🎨 Holi colours' },
              { value: 'leaves', label: '🍂 Falling leaves' },
              { value: 'kites', label: '🪁 Kites' },
              { value: 'rain', label: 'Rain' },
              { value: 'emoji', label: 'My own emoji…' },
            ],
          },
          { key: 'bgFxEmoji', type: 'text', label: 'Emoji for the background effect', help: 'One or more, separated by spaces, e.g. 🧈 🌾 ✨', showIf: { bgFx: ['emoji'] } },
          { key: 'bgFxAmount', type: 'number', label: 'How many (background effect)', help: 'Default 30. Up to 100.' },
          { key: 'image', type: 'image', label: 'Main image', showIf: { art: ['churn', 'image'] } },
          { key: 'images', type: 'images', label: 'Collage photos', max: 7, showIf: { art: ['collage'] } },
          {
            key: 'video',
            type: 'video',
            label: 'Video',
            help: 'MP4, up to 50 MB. Keep it short (5–15 seconds) and under 10 MB so it starts quickly on mobile data. Vertical 9:16 works best for full-screen. Bigger files: upload them to Shopify → Content → Files and paste the link here.',
            showIf: { art: ['video', 'video_full'] },
          },
          { key: 'poster', type: 'image', label: 'Still image shown while the video loads (optional)', showIf: { art: ['video', 'video_full'] } },
          { key: 'videoSound', type: 'boolean', label: 'Play with sound (people can still tap to mute)', showIf: { art: ['video', 'video_full'] } },
          {
            key: 'chips',
            type: 'list',
            label: 'Step chips under the text',
            itemLabel: '{label}',
            fields: [
              { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
              { key: 'label', type: 'text', label: 'Label' },
            ],
          },
          { key: 'showNameInput', type: 'boolean', label: 'Ask for their name (+ photo) on this slide' },
        ],
      },
    ],
  },
  {
    key: 'popup',
    title: 'Launch popup',
    icon: 'message-image-outline',
    description: 'An offer or announcement that pops up when the app opens.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Popup is on' },
      { key: 'id', type: 'text', label: 'Popup ID', help: 'Change this to show a new popup to people who already closed the old one.' },
      {
        key: 'frequency',
        type: 'select',
        label: 'How often',
        options: [
          { value: 'once', label: 'Once per person' },
          { value: 'daily', label: 'Once a day' },
          { value: 'every_launch', label: 'Every time the app opens' },
        ],
      },
      { key: 'image', type: 'image', label: 'Image' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'link', type: 'link', label: 'Button opens', help: LINK_HELP },
      ...schedule,
    ],
  },
  {
    key: 'home',
    title: 'Home screen',
    icon: 'home-outline',
    description: 'Banners and the order of every section on the home screen.',
    fields: [
      { key: 'searchPlaceholder', type: 'text', label: 'Search bar text' },
      {
        key: 'quickTabs',
        type: 'list',
        label: 'Tabs above the banner (ROSIER, Breakfast club…)',
        help: 'Tip: click a tab in the phone preview to edit it there.',
        itemLabel: '{label}',
        newItem: { enabled: true, kind: 'text', label: 'New\ntab', font: 'serif', textColor: '', bgColor: '', borderColor: '', icon: '', iconColor: '', image: '', link: '', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this tab' },
          {
            key: 'kind',
            type: 'select',
            label: 'Shows',
            options: [
              { value: 'text', label: 'Text (with an optional icon above)' },
              { value: 'logo', label: 'Rosier logo' },
              { value: 'image', label: 'An image / logo I upload' },
            ],
          },
          { key: 'label', type: 'textarea', label: 'Text', help: 'Press Enter for a second line.', showIf: { kind: ['text'] } },
          {
            key: 'font',
            type: 'select',
            label: 'Text style',
            options: [
              { value: 'serif', label: 'Serif (like Benefit club)' },
              { value: 'bold', label: 'Bold (like Breakfast club)' },
              { value: 'sans', label: 'Plain' },
            ],
            showIf: { kind: ['text'] },
          },
          { key: 'icon', type: 'icon', label: 'Icon above the text (optional)', help: ICON_HELP, showIf: { kind: ['text'] } },
          { key: 'iconColor', type: 'color', label: 'Icon colour', help: 'Empty = same as the text.', showIf: { kind: ['text'] } },
          { key: 'image', type: 'image', label: 'Image', help: 'A logo or small picture, shown fitted inside the tab.', showIf: { kind: ['image'] } },
          { key: 'textColor', type: 'color', label: 'Text / logo colour', help: 'Empty = theme colour.' },
          { key: 'bgColor', type: 'color', label: 'Background colour', help: 'Empty = theme card colour.' },
          { key: 'borderColor', type: 'color', label: 'Border colour', help: 'Empty = theme border.' },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP + ' Leave empty to do nothing.' },
          ...schedule,
        ],
      },
      { key: 'quickTabsShow', type: 'boolean', label: 'Show the tabs above the banner' },
      { key: 'quickTabWidth', type: 'number', label: 'Tab width (px)', help: 'Default 82.' },
      { key: 'quickTabHeight', type: 'number', label: 'Tab height (px)', help: 'Default 54.' },
      { key: 'showCoinsBanner', type: 'boolean', label: 'Show the Rosier Coins banner first in the slider' },
      {
        key: 'coinsBanner',
        type: 'group',
        label: 'Rosier Coins banner',
        fields: [
          { key: 'title', type: 'textarea', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Text' },
          { key: 'button', type: 'text', label: 'Button text' },
        ],
      },
      {
        key: 'heroSource',
        type: 'select',
        label: 'Top slider shows',
        options: [
          { value: 'website', label: 'Live banners from rosierfoods.com (my banners below when offline)' },
          { value: 'custom', label: 'Only my banners below' },
          { value: 'both', label: 'My banners first, then the website banners' },
        ],
      },
      {
        key: 'heroBanners',
        type: 'list',
        label: 'My slider banners',
        itemLabel: '{title}',
        newItem: { enabled: true, kind: 'image', image: '', title: '', sub: '', colors: ['#FFF3D6', '#E9B955'], light: false, link: '', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this banner' },
          {
            key: 'kind',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'image', label: 'Just my image (designed banner)' },
              { value: 'card', label: 'Colour card with title + floating product photo' },
            ],
          },
          { key: 'image', type: 'image', label: 'Image', help: 'For "Just my image", use a wide banner around 1000 × 800 px.' },
          { key: 'title', type: 'textarea', label: 'Title', showIf: { kind: ['card'] } },
          { key: 'sub', type: 'textarea', label: 'Text', showIf: { kind: ['card'] } },
          { key: 'colors', type: 'colors', label: 'Card gradient', showIf: { kind: ['card'] } },
          { key: 'light', type: 'boolean', label: 'Light text (for dark cards)', showIf: { kind: ['card'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
          ...schedule,
        ],
      },
      {
        key: 'tilesSource',
        type: 'select',
        label: 'Two tiles under the slider',
        options: [
          { value: 'website', label: 'Live from rosierfoods.com' },
          { value: 'custom', label: 'My tiles below' },
          { value: 'none', label: 'Hide' },
        ],
      },
      {
        key: 'tiles',
        type: 'list',
        label: 'My tiles',
        itemLabel: '{link}',
        max: 2,
        newItem: { image: '', link: '' },
        fields: [
          { key: 'image', type: 'image', label: 'Image', help: 'Around 700 × 385 px.' },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
        ],
      },
      {
        key: 'sections',
        type: 'list',
        label: 'Sections (drag to reorder)',
        itemLabel: '{title|type}',
        newItem: { type: 'image', enabled: true, title: '', image: '', link: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this section' },
          { key: 'type', type: 'select', label: 'Section type', options: SECTION_TYPES },
          { key: 'title', type: 'text', label: 'Title', showIf: { type: ['categories', 'deals', 'grid', 'row', 'promo', 'reviews'] } },
          { key: 'subtitle', type: 'text', label: 'Subtitle', showIf: { type: ['grid', 'reviews'] } },
          { key: 'handles', type: 'products', label: 'Products', help: 'Leave empty to fill automatically (deals: biggest discounts; grid/row: the category below).', showIf: { type: ['deals', 'grid', 'row'] } },
          { key: 'category', type: 'category', label: 'Or show a category', showIf: { type: ['grid', 'row'] } },
          { key: 'limit', type: 'number', label: 'How many products', showIf: { type: ['grid'] } },
          { key: 'showViewAll', type: 'boolean', label: 'Show "View all" button', showIf: { type: ['grid'] } },
          { key: 'kicker', type: 'text', label: 'Small text above title', showIf: { type: ['promo'] } },
          { key: 'body', type: 'textarea', label: 'Text', showIf: { type: ['promo'] } },
          { key: 'button', type: 'text', label: 'Button text', showIf: { type: ['promo'] } },
          { key: 'image', type: 'image', label: 'Image', showIf: { type: ['promo', 'image'] } },
          { key: 'colors', type: 'colors', label: 'Background gradient', showIf: { type: ['promo'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP, showIf: { type: ['promo', 'image', 'row'] } },
          { key: 'height', type: 'number', label: 'Height in the app (0 = keep the image’s own shape)', showIf: { type: ['image'] } },
          { key: 'bg', type: 'color', label: 'Section background colour', help: 'Leave empty for none.' },
          { key: 'titleColor', type: 'color', label: 'Title colour', help: 'Leave empty to use the theme colour.', showIf: { type: ['categories', 'deals', 'grid', 'row', 'reviews'] } },
          { key: 'titleSize', type: 'number', label: 'Title size (px)', help: '0 = normal.', showIf: { type: ['categories', 'deals', 'grid', 'row', 'reviews'] } },
          { key: 'spaceAbove', type: 'number', label: 'Extra space above (px)', help: 'Can be negative to pull it closer.' },
          { key: 'spaceBelow', type: 'number', label: 'Extra space below (px)' },
          {
            key: 'animation',
            type: 'select',
            label: 'Entrance animation',
            options: [
              { value: '', label: 'Default' },
              { value: 'fadeUp', label: 'Fade up' },
              { value: 'fadeDown', label: 'Fade down' },
              { value: 'fade', label: 'Fade in' },
              { value: 'zoom', label: 'Zoom in' },
              { value: 'slideLeft', label: 'Slide in from the right' },
              { value: 'slideRight', label: 'Slide in from the left' },
              { value: 'none', label: 'None' },
            ],
          },
          { key: 'animSpeed', type: 'number', label: 'Animation speed (× normal)', help: '1 = normal, 2 = twice as fast, 0.5 = slower.' },
        ],
      },
    ],
  },
  {
    key: 'categories',
    title: 'Categories',
    icon: 'shape-outline',
    description: 'Names, order and pictures of the shop categories.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Categories (drag to reorder)',
        itemLabel: '{label}',
        newItem: { id: '', enabled: true, label: '', icon: 'combo', image: '', blurb: '', tint: '#F4E1C4' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show' },
          { key: 'id', type: 'text', label: 'Category ID', help: 'Products are matched to categories by this ID (ghee, atta, oils, breakfast, immunity, pickles, combos). Assign products to a new ID under Products.' },
          { key: 'label', type: 'text', label: 'Name' },
          { key: 'blurb', type: 'text', label: 'One-line description' },
          {
            key: 'icon',
            type: 'select',
            label: 'Built-in icon',
            options: ['ghee', 'atta', 'oil', 'breakfast', 'immunity', 'pickle', 'combo'].map((v) => ({ value: v, label: v })),
          },
          { key: 'image', type: 'image', label: 'Or your own icon image', help: 'Square PNG with a transparent background works best.' },
          { key: 'tint', type: 'color', label: 'Header colour' },
          { key: 'showBanner', type: 'boolean', label: 'Show the category banner at the top', help: 'Same banner as the website’s collection page (phone version).' },
          { key: 'collection', type: 'text', label: 'Website collection for the banner', help: 'The part after /collections/ on rosierfoods.com, e.g. ghee or stone-press-oil.' },
          { key: 'bannerImage', type: 'image', label: 'Or use my own banner', help: 'Overrides the website banner.' },
          { key: 'bannerLink', type: 'text', label: 'Link when your own banner is tapped (optional)', help: 'e.g. /products/a2-ghee or app:/coins' },
          { key: 'bannerRadius', type: 'number', label: 'Banner corner roundness', help: 'Default 16. 0 = sharp.' },
        ],
      },
    ],
  },
  {
    key: 'products',
    title: 'Products',
    icon: 'basket-outline',
    description: 'Products and prices come live from Shopify. Here you can hide a product in the app or change its badge, category or rating.',
    fields: [
      {
        key: 'overrides',
        type: 'list',
        label: 'Product changes',
        itemLabel: '{handle}',
        newItem: { handle: '', hidden: false, badge: '', category: '', rating: 0, title: '', image: '' },
        fields: [
          { key: 'handle', type: 'product', label: 'Product' },
          { key: 'hidden', type: 'boolean', label: 'Hide from the app' },
          { key: 'title', type: 'text', label: 'Name in the app', help: 'Leave empty to use the Shopify name.' },
          { key: 'badge', type: 'text', label: 'Badge', help: 'e.g. 🔥 Bestseller. Leave empty to keep the current one.' },
          { key: 'category', type: 'category', label: 'Category' },
          { key: 'rating', type: 'number', label: 'Star rating', help: '0 = keep current.' },
          { key: 'image', type: 'image', label: 'Main photo in the app', help: 'Leave empty to use the Shopify photo.' },
        ],
      },
    ],
  },
  {
    key: 'coins',
    title: 'Rosier Coins',
    icon: 'database-outline',
    description: 'Earning rules, vouchers and everything on the Coins screen.',
    fields: [
      { key: 'earnPerRupee', type: 'number', label: 'Coins per ₹1', help: '0.05 = 5 coins for every ₹100.' },
      { key: 'welcomeBonus', type: 'number', label: 'Welcome coins' },
      { key: 'reviewBonus', type: 'number', label: 'Coins for a review' },
      { key: 'referralBonus', type: 'number', label: 'Coins for a referral' },
      { key: 'pendingDays', type: 'number', label: 'Days until coins unlock' },
      { key: 'minCartForVoucher', type: 'number', label: 'Minimum cart (₹) to use a voucher' },
      {
        key: 'vouchers',
        type: 'list',
        label: 'Vouchers',
        itemLabel: '₹{value} for {cost} coins',
        newItem: { id: '', value: 100, cost: 500, code: '', tint: 'brown' },
        fields: [
          { key: 'id', type: 'text', label: 'ID', help: 'Short unique ID, e.g. v100.' },
          { key: 'value', type: 'number', label: 'Discount (₹)' },
          { key: 'cost', type: 'number', label: 'Cost in coins' },
          { key: 'code', type: 'text', label: 'Shopify discount code', help: 'Must exist in Shopify → Discounts.' },
          {
            key: 'tint',
            type: 'select',
            label: 'Colour',
            options: ['copper', 'brown', 'green', 'deep'].map((v) => ({ value: v, label: v })),
          },
        ],
      },
      { key: 'referralMessage', type: 'textarea', label: 'Refer-a-friend share message' },
      {
        key: 'steps',
        type: 'list',
        label: 'How coins work (timeline)',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'promoTitle', type: 'textarea', label: 'Bottom banner title' },
      { key: 'promoBody', type: 'text', label: 'Bottom banner text' },
      { key: 'promoButton', type: 'text', label: 'Bottom banner button' },
      faq('FAQs'),
    ],
  },
  {
    key: 'benefits',
    title: 'Benefits Club',
    icon: 'crown-outline',
    description: 'The gold banner on home and the Benefits Club page.',
    fields: [
      { key: 'bannerTitle', type: 'text', label: 'Banner title' },
      { key: 'bannerSubtitle', type: 'text', label: 'Banner subtitle' },
      { key: 'bannerTagline', type: 'text', label: 'Banner tagline' },
      {
        key: 'bannerPerks',
        type: 'list',
        label: 'Banner perks (5 fit best)',
        itemLabel: '{label}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'label', type: 'textarea', label: 'Label' },
        ],
      },
      { key: 'pageTitle', type: 'text', label: 'Page title' },
      { key: 'pageSubtitle', type: 'text', label: 'Page subtitle' },
      { key: 'cardFooter', type: 'text', label: 'Text on the member card' },
      {
        key: 'perks',
        type: 'list',
        label: 'Page perks',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'plansTitle', type: 'text', label: 'Plans heading' },
      { key: 'popularPlanMonths', type: 'number', label: 'Plan marked POPULAR (months)' },
      { key: 'membershipHandle', type: 'product', label: 'Membership product' },
      { key: 'loginPrompt', type: 'text', label: '“Already a member? Log in” text' },
      { key: 'memberTitle', type: 'text', label: 'Member page title' },
      { key: 'memberSubtitle', type: 'textarea', label: 'Member page subtitle' },
      { key: 'memberTags', type: 'strings', label: 'Shopify customer tags that mean “member”', help: 'Someone is a member if they bought the membership product, or their Shopify customer has one of these tags (not case sensitive).' },
      { key: 'membershipProductId', type: 'text', label: 'Membership product ID in Shopify', help: 'The number at the end of the product’s admin URL. Orders containing it make the customer a member for the plan’s months.' },
      { key: 'memberDiscountPercent', type: 'number', label: 'Member discount %', help: 'Shown on the member card and used for the savings estimate.' },
      { key: 'cartMemberDiscount', type: 'boolean', label: 'Show the member discount in the cart total', help: 'Only switch on if Shopify really gives members this discount at checkout (automatic discount for member customers).' },
      { key: 'gheeTarget', type: 'number', label: 'Free ghee: order total needed (₹)', help: '0 hides the progress bar.' },
      { key: 'gheeTitle', type: 'text', label: 'Free ghee: title' },
      { key: 'renewDays', type: 'number', label: 'Show “Renew” this many days before it ends' },
      { key: 'updatesTitle', type: 'text', label: 'Member updates heading' },
      {
        key: 'updates',
        type: 'list',
        label: 'Member updates (only members see these)',
        help: 'News, member-only offers, drops. Pinned ones stay on top. Turn on “Also send a phone notification” in Notifications to ping members.',
        itemLabel: '{title}',
        newItem: { enabled: true, pinned: false, title: '', body: '', image: '', link: '', date: '', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show' },
          { key: 'pinned', type: 'boolean', label: 'Pin to the top' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Text' },
          { key: 'image', type: 'image', label: 'Image (optional)' },
          { key: 'link', type: 'link', label: 'Button opens (optional)', help: LINK_HELP },
          { key: 'date', type: 'datetime', label: 'Date shown', help: 'Empty = no date.' },
          { key: 'push', type: 'boolean', label: 'Also send to members’ phones when I publish', help: 'Sent once.' },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'reviews',
    title: 'Reviews',
    icon: 'star-outline',
    description: 'Customer reviews on the home screen.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Reviews',
        itemLabel: '{name} — {title}',
        newItem: { title: '', body: '', name: '', product: '', rating: 5, photo: '' },
        fields: [
          { key: 'title', type: 'text', label: 'Headline' },
          { key: 'body', type: 'textarea', label: 'Review' },
          { key: 'name', type: 'text', label: 'Customer name' },
          { key: 'product', type: 'text', label: 'Product name' },
          { key: 'rating', type: 'number', label: 'Stars (1–5)' },
          { key: 'photo', type: 'image', label: 'Customer photo (optional)' },
        ],
      },
    ],
  },
  {
    key: 'pillars',
    title: 'Rosier experience',
    icon: 'sprout-outline',
    description: 'The four pillars on home and Our Story.',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'subtitle', type: 'text', label: 'Subtitle' },
      {
        key: 'items',
        type: 'list',
        label: 'Pillars',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
    ],
  },
  {
    key: 'account',
    title: 'Login & account',
    icon: 'account-key-outline',
    description: 'Text on the login screen and the login prompts. Switch login on under Shopify connection.',
    fields: [
      { key: 'loginTitle', type: 'text', label: 'Login screen title' },
      { key: 'loginBody', type: 'textarea', label: 'Login screen text' },
      { key: 'loginButton', type: 'text', label: 'Login button' },
      { key: 'skipLabel', type: 'text', label: '"Not now" button' },
      {
        key: 'perks',
        type: 'list',
        label: 'Reasons to log in',
        itemLabel: '{text}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'text', type: 'text', label: 'Text' },
        ],
      },
      { key: 'checkoutPromptTitle', type: 'text', label: 'Checkout prompt title', help: 'Shown when someone taps Checkout without logging in.' },
      { key: 'checkoutPromptBody', type: 'textarea', label: 'Checkout prompt text' },
      { key: 'guestLabel', type: 'text', label: '"Continue as guest" button' },
      { key: 'profileCardTitle', type: 'text', label: 'Profile tab: login card title' },
      { key: 'profileCardBody', type: 'text', label: 'Profile tab: login card text' },
      { key: 'ordersLoginPrompt', type: 'text', label: 'Orders screen: login prompt' },
    ],
  },
  {
    key: 'announcements',
    title: 'Notifications',
    icon: 'bell-outline',
    description: 'Messages for the app’s notification inbox. Tick “Also send to phones” and they pop up on phones too (even with the app closed) when you publish. Order updates go out automatically — see Phone notifications.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Messages',
        itemLabel: '{title}',
        newItem: { id: '', title: '', body: '', link: '', push: true, audience: 'all' },
        autoId: true,
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
          { key: 'link', type: 'link', label: 'Opens when tapped (optional)', help: LINK_HELP },
          { key: 'push', type: 'boolean', label: 'Also send to phones when I publish', help: 'Pops up on their phone even when the app is closed. Sent once.' },
          {
            key: 'audience',
            type: 'select',
            label: 'Send to',
            options: AUDIENCES,
            showIf: { push: [true] },
          },
        ],
      },
    ],
  },
  {
    key: 'push',
    title: 'Phone notifications',
    icon: 'cellphone-message',
    description: 'Notifications that pop up on customers’ phones, even when the app is closed. Send offers from Notifications (or Send now on the Push page); order updates go out by themselves.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Send phone notifications', help: 'Main switch for everything below.' },
      {
        key: 'sound',
        type: 'select',
        label: 'Notification sound',
        help: 'Press ▶ to listen. Applies to every notification sent after you publish.',
        options: [
          { value: 'chime', label: 'Rosier chime (two soft notes)' },
          { value: 'bell', label: 'Temple bell' },
          { value: 'coin', label: 'Coin ping' },
          { value: 'soft', label: 'Soft rising notes' },
          { value: 'default', label: 'Phone’s default sound' },
        ],
      },
      { key: 'askTitle', type: 'text', label: 'Ask-for-permission title', help: 'Shown in the app before the phone asks “Allow notifications?”.' },
      { key: 'askBody', type: 'textarea', label: 'Ask-for-permission text' },
      { key: 'askButton', type: 'text', label: 'Ask-for-permission button' },
      { key: 'liveCard', type: 'boolean', label: 'Show the live “Your order” card on the home screen' },
      {
        key: 'orders',
        type: 'group',
        label: 'Order updates (sent automatically)',
        help: 'Use {order} for the order number, {name} for their first name, {courier} for the courier.',
        fields: [
          {
            key: 'placed',
            type: 'group',
            label: 'Order confirmed',
            fields: [
              { key: 'enabled', type: 'boolean', label: 'Send this' },
              { key: 'title', type: 'text', label: 'Title' },
              { key: 'body', type: 'textarea', label: 'Message' },
            ],
          },
          {
            key: 'shipped',
            type: 'group',
            label: 'Shipped',
            fields: [
              { key: 'enabled', type: 'boolean', label: 'Send this' },
              { key: 'title', type: 'text', label: 'Title' },
              { key: 'body', type: 'textarea', label: 'Message' },
            ],
          },
          {
            key: 'out',
            type: 'group',
            label: 'Out for delivery',
            fields: [
              { key: 'enabled', type: 'boolean', label: 'Send this' },
              { key: 'title', type: 'text', label: 'Title' },
              { key: 'body', type: 'textarea', label: 'Message' },
            ],
          },
          {
            key: 'delivered',
            type: 'group',
            label: 'Delivered',
            fields: [
              { key: 'enabled', type: 'boolean', label: 'Send this' },
              { key: 'title', type: 'text', label: 'Title' },
              { key: 'body', type: 'textarea', label: 'Message' },
            ],
          },
          {
            key: 'cancelled',
            type: 'group',
            label: 'Cancelled',
            fields: [
              { key: 'enabled', type: 'boolean', label: 'Send this' },
              { key: 'title', type: 'text', label: 'Title' },
              { key: 'body', type: 'textarea', label: 'Message' },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'about',
    title: 'Our Story',
    icon: 'book-open-page-variant-outline',
    fields: [
      { key: 'heroImage', type: 'image', label: 'Top image (optional)' },
      { key: 'headline', type: 'textarea', label: 'Headline' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      {
        key: 'blocks',
        type: 'list',
        label: 'Blocks',
        itemLabel: '{title}',
        newItem: { type: 'text', title: '', body: '', signature: '', image: '' },
        fields: [
          {
            key: 'type',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'text', label: 'Heading + text' },
              { value: 'quote', label: 'Quote card' },
            ],
          },
          { key: 'title', type: 'text', label: 'Heading' },
          { key: 'body', type: 'textarea', label: 'Text', help: 'Leave a blank line between paragraphs.' },
          { key: 'signature', type: 'text', label: 'Signature', showIf: { type: ['quote'] } },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      { key: 'labReportsPath', type: 'text', label: 'Lab reports page on the website' },
      { key: 'websitePath', type: 'text', label: 'About page on the website' },
    ],
  },
  {
    key: 'blog',
    title: 'Blog',
    icon: 'newspaper-variant-outline',
    fields: [
      {
        key: 'articles',
        type: 'list',
        label: 'Articles',
        itemLabel: '{title}',
        autoId: true,
        newItem: { id: '', enabled: true, title: '', kicker: '', mins: 2, icon: 'leaf', colors: ['#F6D98C', '#C98A52'], image: '', product: '', body: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Published' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'kicker', type: 'text', label: 'Tag (e.g. Tradition)' },
          { key: 'mins', type: 'number', label: 'Minutes to read' },
          { key: 'image', type: 'image', label: 'Cover image', help: 'If empty, the icon on a colour gradient is used.' },
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'colors', type: 'colors', label: 'Cover gradient' },
          { key: 'body', type: 'textarea', label: 'Article', rows: 12, help: 'Leave a blank line between paragraphs.' },
          { key: 'product', type: 'product', label: '"Shop the product" button' },
        ],
      },
    ],
  },
  {
    key: 'gifting',
    title: 'Gifting',
    icon: 'gift-outline',
    fields: [
      { key: 'image', type: 'image', label: 'Header image (optional)' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'email', type: 'text', label: 'Enquiry email' },
      { key: 'subject', type: 'text', label: 'Email subject' },
      { key: 'category', type: 'category', label: 'Products shown' },
    ],
  },
  {
    key: 'help',
    title: 'Help & Support',
    icon: 'lifebuoy',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      { key: 'phone', type: 'text', label: 'Phone (with +91)' },
      { key: 'phoneLabel', type: 'text', label: 'Phone as shown' },
      { key: 'email', type: 'text', label: 'Email' },
      { key: 'contactPath', type: 'text', label: 'Contact page on the website' },
      faq('FAQs'),
      { key: 'company', type: 'text', label: 'Company name' },
      { key: 'address', type: 'textarea', label: 'Address' },
    ],
  },
  {
    key: 'productPage',
    title: 'Product page',
    icon: 'package-variant-closed',
    description: 'The single product page: photo size, the A+ banners, Description / Benefits / Nutrition tabs and reviews — all read live from the product on rosierfoods.com (phone view).',
    fields: [
      { key: 'heroHeight', type: 'number', label: 'Top photo height (% of screen)', help: 'Default 58.' },
      {
        key: 'heroFit',
        type: 'select',
        label: 'First photo',
        options: [
          { value: 'contain', label: 'Show the whole photo' },
          { value: 'cover', label: 'Fill the area (crops edges)' },
        ],
      },
      { key: 'heroBg', type: 'color', label: 'Behind the top photos' },
      { key: 'showAplus', type: 'boolean', label: 'Show the A+ banners (same as the website)' },
      { key: 'aplusGap', type: 'number', label: 'A+ banners: gap between images (px)' },
      { key: 'aplusRadius', type: 'number', label: 'A+ banners: corner roundness' },
      { key: 'aplusMargin', type: 'number', label: 'A+ banners: side margin (px)', help: '0 = edge to edge.' },
      { key: 'showTabs', type: 'boolean', label: 'Show Description / Key Benefits / Nutrition / Product info tabs' },
      { key: 'showReviews', type: 'boolean', label: 'Show reviews (Judge.me, same as the website)' },
      { key: 'reviewsTitle', type: 'text', label: 'Reviews heading' },
      { key: 'reviewsPerPage', type: 'number', label: 'Reviews shown at a time', help: 'Default 5.' },
      { key: 'allowWrite', type: 'boolean', label: 'Let customers write a review' },
      { key: 'writeButton', type: 'text', label: '“Write a review” button text' },
      { key: 'thanks', type: 'text', label: 'Message after sending a review' },
      { key: 'starColor', type: 'color', label: 'Star colour' },
    ],
  },
  {
    key: 'webPages',
    title: 'Website pages in the app',
    icon: 'web',
    description: 'Show a rosierfoods.com page inside the app, looking exactly like the website on a phone (e.g. the Gift Hampers page). Link to it with app:/page/<page handle>.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Pages',
        itemLabel: '{title}',
        newItem: { enabled: true, handle: '', title: '', hideSiteChrome: true, extraCss: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'On' },
          { key: 'handle', type: 'text', label: 'Website page', help: 'The part after /pages/ — e.g. hampers for rosierfoods.com/pages/hampers. Opens in the app at app:/page/hampers.' },
          { key: 'title', type: 'text', label: 'Title in the app' },
          { key: 'hideSiteChrome', type: 'boolean', label: 'Hide the website’s header, footer and chat buttons', help: 'So it feels like part of the app.' },
          { key: 'extraCss', type: 'textarea', label: 'Extra CSS (advanced, optional)' },
        ],
      },
    ],
  },
  {
    key: 'cartFx',
    title: 'Add to cart animations',
    icon: 'cart-heart',
    description: 'What happens when someone adds something to the cart: the pop-up message (text, colours, animation) and any number of effects at once. Press “Try it” in the preview to see it.',
    fields: [
      { key: 'toastEnabled', type: 'boolean', label: 'Show the pop-up message' },
      { key: 'toastText', type: 'text', label: 'Message', help: '{coins} = coins they’ll earn, {product} = product name. E.g. “{product} added 🛒 · +{coins} coins”' },
      {
        key: 'toastAnim',
        type: 'select',
        label: 'Message animation',
        options: [
          { value: 'slideDown', label: 'Slide in (default)' },
          { value: 'slideUp', label: 'Slide up from the bottom' },
          { value: 'fade', label: 'Fade in' },
          { value: 'zoom', label: 'Zoom / pop' },
          { value: 'bounce', label: 'Bounce' },
          { value: 'flip', label: 'Flip' },
          { value: 'lightspeed', label: 'Zip in (light speed)' },
        ],
      },
      {
        key: 'toastPosition',
        type: 'select',
        label: 'Message position',
        options: [
          { value: 'top', label: 'Top' },
          { value: 'center', label: 'Middle' },
          { value: 'bottom', label: 'Bottom (above the tab bar)' },
        ],
      },
      {
        key: 'toastIcon',
        type: 'select',
        label: 'Icon in the message',
        options: [
          { value: 'coin', label: 'Spinning Rosier coin' },
          { value: 'check', label: 'Tick' },
          { value: 'cart', label: 'Cart' },
          { value: 'gift', label: 'Gift' },
          { value: 'heart', label: 'Heart' },
          { value: 'emoji', label: 'My own emoji' },
          { value: 'none', label: 'No icon' },
        ],
      },
      { key: 'toastEmoji', type: 'text', label: 'Emoji for the message', showIf: { toastIcon: ['emoji'] } },
      { key: 'toastBg', type: 'color', label: 'Message background' },
      { key: 'toastTextColor', type: 'color', label: 'Message text colour' },
      { key: 'toastIconColor', type: 'color', label: 'Icon colour' },
      { key: 'toastRadius', type: 'number', label: 'Corner roundness', help: 'Default 18. 0 = sharp, 30 = pill.' },
      { key: 'toastSeconds', type: 'number', label: 'Show for (seconds)', help: 'Default 2.2.' },
      { key: 'fly', type: 'boolean', label: '✈️ Product photo flies into the cart' },
      { key: 'cartBounce', type: 'boolean', label: '🛒 Cart icon bounces' },
      { key: 'bigTick', type: 'boolean', label: '✅ Big tick pops up in the middle' },
      { key: 'sparkles', type: 'boolean', label: '✦ Golden sparkles' },
      { key: 'confetti', type: 'boolean', label: '🎉 Confetti' },
      { key: 'hearts', type: 'boolean', label: '♥ Hearts' },
      { key: 'coins', type: 'boolean', label: '🪙 Coin shower' },
      { key: 'petals', type: 'boolean', label: '🌸 Flower petals' },
      { key: 'emoji', type: 'text', label: 'Your own emoji shower (optional)', help: 'E.g. 🧈 🌾 — leave empty for none.' },
      { key: 'burstAmount', type: 'number', label: 'How many (all showers together)', help: 'Default 26.' },
      { key: 'burstSeconds', type: 'number', label: 'Showers last (seconds)', help: 'Default 1.6.' },
      { key: 'haptic', type: 'boolean', label: 'Little phone vibration' },
    ],
  },
  {
    key: 'rewards',
    title: 'Cart rewards & free gifts',
    icon: 'gift-open-outline',
    description: 'Like the website: “Add ₹X more to get a free gift”. When the cart reaches the amount, the gift is added automatically (and removed if the cart drops below). Use “Import from Shopify” to copy your automatic discounts.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Cart rewards on' },
      { key: 'showBar', type: 'boolean', label: 'Show the progress bar in the cart' },
      { key: 'barTitle', type: 'text', label: 'Progress bar title' },
      {
        key: 'items',
        type: 'list',
        label: 'Rewards (lowest amount first)',
        help: 'For a free gift the gift must really be free at checkout: create it in Shopify as an automatic “Buy X get Y” / free-gift discount (as on the website), or use a ₹0 product.',
        itemLabel: '{title} — ₹{minAmount}',
        newItem: { enabled: true, kind: 'gift', title: '🎁 Free gift', minAmount: 999, variantId: '', giftTitle: '', giftImage: '', qty: 1, autoAdd: true, lockedText: 'Add ₹{left} more to get a FREE {gift}', unlockedText: '{gift} added free to your order', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'On' },
          {
            key: 'kind',
            type: 'select',
            label: 'Reward',
            options: [
              { value: 'gift', label: 'Free gift (added to the cart automatically)' },
              { value: 'shipping', label: 'Free shipping (message only)' },
              { value: 'info', label: 'Other offer (message only, e.g. extra % off at checkout)' },
            ],
          },
          { key: 'title', type: 'text', label: 'Name shown on the progress bar', help: 'e.g. 🎁 Pickle Mystery Gift' },
          { key: 'minAmount', type: 'number', label: 'Cart amount needed (₹)' },
          { key: 'variantId', type: 'text', label: 'Gift: Shopify variant ID', help: 'The number from Shopify → product → variant URL (…/variants/12345). The product can be hidden from the website.', showIf: { kind: ['gift'] } },
          { key: 'giftTitle', type: 'text', label: 'Gift name in the cart', showIf: { kind: ['gift'] } },
          { key: 'giftImage', type: 'image', label: 'Gift picture', showIf: { kind: ['gift'] } },
          { key: 'qty', type: 'number', label: 'How many', showIf: { kind: ['gift'] } },
          { key: 'autoAdd', type: 'boolean', label: 'Add it to the cart automatically', showIf: { kind: ['gift'] } },
          { key: 'lockedText', type: 'text', label: 'Text before unlocking', help: '{left} = amount still needed, {gift} = gift name, {amount} = target.' },
          { key: 'unlockedText', type: 'text', label: 'Text once unlocked' },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'coupons',
    title: 'Coupons',
    icon: 'ticket-percent-outline',
    description: 'The coupon box in the cart and the list of offers customers can tap to apply. Create the actual discount codes in Shopify → Discounts — the app checks every code with Shopify before checkout.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show the coupon box in the cart' },
      { key: 'boxTitle', type: 'text', label: 'Coupon box title' },
      { key: 'placeholder', type: 'text', label: 'Hint inside the box' },
      { key: 'showList', type: 'boolean', label: 'Show “Available coupons” list' },
      { key: 'listTitle', type: 'text', label: 'List title' },
      {
        key: 'items',
        type: 'list',
        label: 'Coupons shown to customers',
        help: 'Use “Import from Shopify” to fill this from your Shopify discounts. Codes not listed here still work if typed in.',
        itemLabel: '{code} — {title}',
        newItem: { enabled: true, code: '', title: '', description: '', kind: 'percent', value: 10, minOrder: 0, maxDiscount: 0, startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this coupon' },
          { key: 'code', type: 'text', label: 'Code', help: 'Exactly as created in Shopify → Discounts.' },
          { key: 'title', type: 'text', label: 'Headline', help: 'e.g. Flat ₹100 off on ₹999+' },
          { key: 'description', type: 'textarea', label: 'Details / terms' },
          {
            key: 'kind',
            type: 'select',
            label: 'Discount type',
            help: 'Used to show the saving before Shopify confirms it.',
            options: [
              { value: 'percent', label: '% off' },
              { value: 'flat', label: '₹ off' },
              { value: 'freeship', label: 'Free shipping' },
              { value: 'other', label: 'Other (buy X get Y, gift…)' },
            ],
          },
          { key: 'value', type: 'number', label: 'Amount (% or ₹)', showIf: { kind: ['percent', 'flat'] } },
          { key: 'minOrder', type: 'number', label: 'Minimum order (₹)', help: '0 = no minimum.' },
          { key: 'maxDiscount', type: 'number', label: 'Maximum discount (₹)', help: '0 = no cap.', showIf: { kind: ['percent'] } },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'tracking',
    title: 'Order tracking',
    icon: 'truck-fast-outline',
    description: 'The “Track order” screen. Logged-in customers see live courier status on each order; anyone can track with order number + email/phone (needs the Admin API connected).',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show “Track order” in the app' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      { key: 'orderLabel', type: 'text', label: 'Order number label' },
      { key: 'contactLabel', type: 'text', label: 'Email / phone label' },
      { key: 'help', type: 'textarea', label: 'Note under the tracking timeline' },
      { key: 'websiteTrackUrl', type: 'text', label: 'Courier tracking page (optional)', help: 'Used when Shopify has a tracking number but no link. Put {number} where the tracking number goes, e.g. https://shiprocket.co/tracking/{number}' },
      {
        key: 'steps',
        type: 'group',
        label: 'Timeline step names',
        fields: [
          { key: 'ordered', type: 'text', label: 'Step 1' },
          { key: 'confirmed', type: 'text', label: 'Step 2' },
          { key: 'shipped', type: 'text', label: 'Step 3' },
          { key: 'out', type: 'text', label: 'Step 4' },
          { key: 'delivered', type: 'text', label: 'Step 5' },
        ],
      },
    ],
  },
  {
    key: 'search',
    title: 'Search',
    icon: 'magnify',
    fields: [{ key: 'popular', type: 'strings', label: 'Popular searches' }],
  },
  {
    key: 'effects',
    title: 'Seasonal effects',
    icon: 'snowflake',
    description: 'Snow for winter, sparkles for Diwali, colours for Holi… Falls gently over the app without blocking taps. Turn it on, pick an effect, publish.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show seasonal effects in the app', help: 'The main on/off switch. Off = no effects anywhere.' },
      { key: 'userToggle', type: 'boolean', label: 'Let customers turn effects off in their Profile' },
      {
        key: 'items',
        type: 'list',
        label: 'Effects',
        help: 'The first effect in this list that is switched on (and inside its dates) is the one shown. Set dates to run one automatically, e.g. snow from 1 Dec to 31 Jan.',
        itemLabel: '{name}',
        newItem: { enabled: true, name: 'New effect', type: 'snow', amount: 40, speed: 1, size: 1, opacity: 0.9, colors: [], emoji: '', image: '', screens: 'home', stopAfter: 0, startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Switched on' },
          { key: 'name', type: 'text', label: 'Name (only you see this)' },
          {
            key: 'type',
            type: 'select',
            label: 'Effect',
            options: [
              { value: 'snow', label: '❄️ Snowfall (winter / Christmas)' },
              { value: 'sparkles', label: '✨ Golden sparkles (Diwali)' },
              { value: 'diyas', label: '🪔 Floating diyas (Diwali)' },
              { value: 'holi', label: '🎨 Holi colours' },
              { value: 'rain', label: '🌧️ Rain (monsoon)' },
              { value: 'confetti', label: '🎉 Confetti (sale / celebration)' },
              { value: 'petals', label: '🌸 Falling petals (spring / wedding season)' },
              { value: 'hearts', label: '💛 Hearts (Valentine’s / Mother’s Day)' },
              { value: 'leaves', label: '🍂 Autumn leaves' },
              { value: 'kites', label: '🪁 Kites (Sankranti)' },
              { value: 'emoji', label: 'Your own emoji' },
              { value: 'image', label: 'Your own image' },
            ],
          },
          { key: 'emoji', type: 'text', label: 'Emoji to use', help: 'One or more, separated by spaces, e.g. 🥭 🌞', showIf: { type: ['emoji'] } },
          { key: 'image', type: 'image', label: 'Image to use', help: 'A small PNG with a transparent background works best (e.g. a coin, a flower).', showIf: { type: ['image'] } },
          { key: 'amount', type: 'number', label: 'How many at once', help: '10 = a few, 40 = normal, 80 = heavy.' },
          { key: 'speed', type: 'number', label: 'Speed (× normal)', help: '1 = normal, 0.5 = slow and dreamy, 2 = fast.' },
          { key: 'size', type: 'number', label: 'Size (× normal)', help: '1 = normal.' },
          { key: 'opacity', type: 'number', label: 'Strength (0–1)', help: '1 = fully visible, 0.5 = subtle.' },
          { key: 'colors', type: 'colors', label: 'Colours', help: 'Leave empty for the effect’s own colours.', showIf: { type: ['snow', 'sparkles', 'holi', 'rain', 'confetti', 'petals', 'hearts'] } },
          {
            key: 'screens',
            type: 'select',
            label: 'Where it shows',
            options: [
              { value: 'home', label: 'Home screen only' },
              { value: 'tabs', label: 'Main tabs (Home, Shop, Coins, Cart, Profile)' },
              { value: 'all', label: 'Every screen' },
            ],
          },
          { key: 'stopAfter', type: 'number', label: 'Stop after (seconds)', help: '0 = keeps going. 8 = a short burst each time the app opens.' },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'theme',
    title: 'Theme & sizes',
    icon: 'palette-outline',
    description: 'Colours and sizes across the app. Watch the phone on the right while you change them.',
    fields: [
      {
        key: 'light',
        type: 'group',
        label: 'Colours — light mode',
        fields: [
          { key: 'bg', type: 'color', label: 'Page background' },
          { key: 'header', type: 'color', label: 'Top bar background' },
          { key: 'card', type: 'color', label: 'Soft card / tile background' },
          { key: 'cardStrong', type: 'color', label: 'White card background' },
          { key: 'border', type: 'color', label: 'Lines & borders' },
          { key: 'text', type: 'color', label: 'Main text' },
          { key: 'textSoft', type: 'color', label: 'Secondary text' },
          { key: 'textMute', type: 'color', label: 'Faint text (hints, placeholders)' },
          { key: 'heading', type: 'color', label: 'Headings' },
          { key: 'primary', type: 'color', label: 'Brand colour (buttons, links)' },
          { key: 'accent', type: 'color', label: 'Accent' },
          { key: 'deepAlt', type: 'color', label: 'Dark brown (badges, buttons)' },
          { key: 'gold', type: 'color', label: 'Gold (coins, stars)' },
          { key: 'price', type: 'color', label: 'Price colour' },
          { key: 'green', type: 'color', label: 'Discount / success green' },
          { key: 'tabBar', type: 'color', label: 'Bottom tab bar' },
          { key: 'imageBg', type: 'color', label: 'Behind product photos', help: 'Empty = soft card colour.' },
        ],
      },
      {
        key: 'dark',
        type: 'group',
        label: 'Colours — dark mode',
        fields: [
          { key: 'bg', type: 'color', label: 'Page background' },
          { key: 'header', type: 'color', label: 'Top bar background' },
          { key: 'card', type: 'color', label: 'Soft card / tile background' },
          { key: 'cardStrong', type: 'color', label: 'White card background' },
          { key: 'border', type: 'color', label: 'Lines & borders' },
          { key: 'text', type: 'color', label: 'Main text' },
          { key: 'textSoft', type: 'color', label: 'Secondary text' },
          { key: 'textMute', type: 'color', label: 'Faint text (hints, placeholders)' },
          { key: 'heading', type: 'color', label: 'Headings' },
          { key: 'primary', type: 'color', label: 'Brand colour (buttons, links)' },
          { key: 'accent', type: 'color', label: 'Accent' },
          { key: 'deepAlt', type: 'color', label: 'Dark brown (badges, buttons)' },
          { key: 'gold', type: 'color', label: 'Gold (coins, stars)' },
          { key: 'price', type: 'color', label: 'Price colour' },
          { key: 'green', type: 'color', label: 'Discount / success green' },
          { key: 'tabBar', type: 'color', label: 'Bottom tab bar' },
          { key: 'imageBg', type: 'color', label: 'Behind product photos', help: 'Empty = soft card colour.' },
        ],
      },
      {
        key: 'layout',
        type: 'group',
        label: 'Sizes',
        fields: [
          { key: 'heroCardHeight', type: 'number', label: 'Top slider: colour card height (px)', help: 'Default 212. Used when the slider shows colour cards, not images.' },
          { key: 'heroImageRatio', type: 'number', label: 'Top slider: image shape (width ÷ height)', help: '0 = automatic (matches your banner images). 1.25 = slightly wide, 1 = square, 2 = wide strip.' },
          { key: 'heroRadius', type: 'number', label: 'Top slider: corner roundness', help: 'Default 22. 0 = sharp corners.' },
          { key: 'carouselSeconds', type: 'number', label: 'Top slider: seconds per slide', help: 'Default 4.2. 0 = don’t auto-slide.' },
          { key: 'tileRatio', type: 'number', label: 'Tiles under the slider: height ÷ width', help: 'Default 0.55.' },
          { key: 'tileRadius', type: 'number', label: 'Tiles: corner roundness', help: 'Default 16.' },
          { key: 'categoryTile', type: 'number', label: 'Category tile width (px)', help: 'Default 72.' },
          { key: 'categoryIcon', type: 'number', label: 'Category icon size (px)', help: 'Default 44.' },
          { key: 'dealCardWidth', type: 'number', label: 'Deal card width (px)', help: 'Default 160 — the cards in sideways rows.' },
          { key: 'productImageRatio', type: 'number', label: 'Product photo height (× card width)', help: 'Default 0.9. Bigger = taller photos.' },
          { key: 'cardRadius', type: 'number', label: 'Product card corner roundness', help: 'Default 20.' },
          { key: 'imageBannerRadius', type: 'number', label: 'Image banners: corner roundness', help: 'Default 18.' },
          { key: 'sectionSpacing', type: 'number', label: 'Space between home sections (× normal)', help: 'Default 1. 0.5 = tighter, 1.5 = more air.' },
          { key: 'gridColumns', type: 'number', label: 'Products per row on Shop / category pages', help: '1, 2 or 3. Default 2.' },
          { key: 'listImageScale', type: 'number', label: 'Product photo size inside its box (%)', help: 'Default 92. 100 = fills the box.' },
          {
            key: 'listImageFit',
            type: 'select',
            label: 'Product photos in lists',
            options: [
              { value: 'contain', label: 'Show the whole photo' },
              { value: 'cover', label: 'Fill the box (crops edges)' },
            ],
          },
          { key: 'dealImageScale', type: 'number', label: 'Deal card photo size (%)', help: 'Default 100.' },
        ],
      },
    ],
  },
  {
    key: 'general',
    title: 'App settings',
    icon: 'cog-outline',
    description: 'Logo, maintenance mode and forcing users to update.',
    fields: [
      { key: 'logo', type: 'image', label: 'Logo', help: 'Black logo on a transparent background — the app recolours it.' },
      { key: 'tagline', type: 'text', label: 'Tagline' },
      { key: 'footerNote', type: 'text', label: 'Home footer line' },
      {
        key: 'welcomeNotification',
        type: 'group',
        label: 'First notification new users get',
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
        ],
      },
      {
        key: 'maintenance',
        type: 'group',
        label: 'Maintenance mode',
        fields: [
          { key: 'enabled', type: 'boolean', label: 'App is in maintenance (blocks the whole app)' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      {
        key: 'update',
        type: 'group',
        label: 'App update prompt',
        fields: [
          { key: 'minVersion', type: 'text', label: 'Minimum app version', help: 'People on an older version see the update prompt. Current app version is 1.0.0.' },
          { key: 'force', type: 'boolean', label: 'Block the app until they update' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'androidUrl', type: 'text', label: 'Play Store link' },
          { key: 'iosUrl', type: 'text', label: 'App Store link' },
        ],
      },
    ],
  },
];

export const SECTION_KEYS = SCHEMA.map((s) => s.key);
