/**
 * Describes every editable section of the app for the admin panel.
 * The admin panel renders its forms from this file, so adding a field here
 * (and reading it in the app) is all it takes to make something editable.
 *
 * Field types:
 *  text, textarea, number, boolean, color, image, images, link, icon,
 *  select (options), datetime, product, products, category, colors, video,
 *  list (of `fields`), group (of `fields`), strings (list of short texts)
 */

const LINK_HELP = 'A product (/products/handle), a collection (/collections/ghee), an app screen (app:/coins) or any https:// link.';
const ICON_HELP = 'Any Material Design icon name, e.g. gift-outline. Browse them at pictogrammers.com/library/mdi';

const schedule = [
  { key: 'startAt', type: 'datetime', label: 'Show from', help: 'Leave empty to show right away.' },
  { key: 'endAt', type: 'datetime', label: 'Show until', help: 'Leave empty to keep showing.' },
];

const faq = (label = 'Questions') => ({
  key: 'faq',
  type: 'list',
  label,
  itemLabel: '{q}',
  fields: [
    { key: 'q', type: 'text', label: 'Question' },
    { key: 'a', type: 'textarea', label: 'Answer', help: 'You can use {per100}, {pendingDays}, {welcomeBonus}.' },
  ],
});

const SECTION_TYPES = [
  { value: 'categories', label: 'Category icons' },
  { value: 'deals', label: 'Deals row (biggest discounts)' },
  { value: 'benefits', label: 'Benefits Club banner' },
  { value: 'grid', label: 'Product grid' },
  { value: 'row', label: 'Product row (scrolls sideways)' },
  { value: 'promo', label: 'Promo strip (image + text)' },
  { value: 'image', label: 'Full-width image banner' },
  { value: 'reviews', label: 'Customer reviews' },
  { value: 'pillars', label: 'Rosier experience (4 pillars)' },
];

export const SCHEMA = [
  {
    key: 'onboarding',
    title: 'Intro slides',
    icon: 'presentation-play',
    description: 'The slides people see the first time they open the app. Raise "Show again version" to show them to everyone once more.',
    fields: [
      { key: 'reshowVersion', type: 'number', label: 'Show again version', help: 'Increase by 1 and publish: every user sees the intro slides again on their next app open.' },
      { key: 'background', type: 'color', label: 'Background colour' },
      { key: 'accent', type: 'color', label: 'Title colour' },
      { key: 'skipLabel', type: 'text', label: 'Skip button text' },
      { key: 'buttonLabel', type: 'text', label: 'Last button text' },
      { key: 'namePlaceholder', type: 'text', label: 'Name box placeholder' },
      { key: 'welcomeNote', type: 'text', label: 'Welcome coins note', help: '{welcomeBonus} becomes the welcome coin amount.' },
      {
        key: 'slides',
        type: 'list',
        label: 'Slides',
        itemLabel: '{title}',
        newItem: { enabled: true, art: 'image', showLogo: false, title: 'NEW SLIDE', sub: '', image: '', images: [], chips: [], showNameInput: false },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this slide' },
          {
            key: 'art',
            type: 'select',
            label: 'Animation',
            options: [
              { value: 'collage', label: 'Floating photo collage (up to 7 photos)' },
              { value: 'churn', label: 'Spinning rings around one photo' },
              { value: 'coins', label: 'Falling Rosier coins' },
              { value: 'image', label: 'One big floating image' },
              { value: 'video', label: 'Video in a rounded frame' },
              { value: 'video_full', label: 'Full-screen video behind the text' },
            ],
          },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'sub', type: 'textarea', label: 'Text' },
          { key: 'showLogo', type: 'boolean', label: 'Show Rosier logo above title' },
          { key: 'image', type: 'image', label: 'Main image', showIf: { art: ['churn', 'image'] } },
          { key: 'images', type: 'images', label: 'Collage photos', max: 7, showIf: { art: ['collage'] } },
          {
            key: 'video',
            type: 'video',
            label: 'Video',
            help: 'MP4, up to 50 MB. Keep it short (5–15 seconds) and under 10 MB so it starts quickly on mobile data. Vertical 9:16 works best for full-screen. Bigger files: upload them to Shopify → Content → Files and paste the link here.',
            showIf: { art: ['video', 'video_full'] },
          },
          { key: 'poster', type: 'image', label: 'Still image shown while the video loads (optional)', showIf: { art: ['video', 'video_full'] } },
          { key: 'videoSound', type: 'boolean', label: 'Play with sound (people can still tap to mute)', showIf: { art: ['video', 'video_full'] } },
          {
            key: 'chips',
            type: 'list',
            label: 'Step chips under the text',
            itemLabel: '{label}',
            fields: [
              { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
              { key: 'label', type: 'text', label: 'Label' },
            ],
          },
          { key: 'showNameInput', type: 'boolean', label: 'Ask for their name (+ photo) on this slide' },
        ],
      },
    ],
  },
  {
    key: 'popup',
    title: 'Launch popup',
    icon: 'message-image-outline',
    description: 'An offer or announcement that pops up when the app opens.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Popup is on' },
      { key: 'id', type: 'text', label: 'Popup ID', help: 'Change this to show a new popup to people who already closed the old one.' },
      {
        key: 'frequency',
        type: 'select',
        label: 'How often',
        options: [
          { value: 'once', label: 'Once per person' },
          { value: 'daily', label: 'Once a day' },
          { value: 'every_launch', label: 'Every time the app opens' },
        ],
      },
      { key: 'image', type: 'image', label: 'Image' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'link', type: 'link', label: 'Button opens', help: LINK_HELP },
      ...schedule,
    ],
  },
  {
    key: 'home',
    title: 'Home screen',
    icon: 'home-outline',
    description: 'Banners and the order of every section on the home screen.',
    fields: [
      { key: 'searchPlaceholder', type: 'text', label: 'Search bar text' },
      { key: 'showCoinsBanner', type: 'boolean', label: 'Show the Rosier Coins banner first in the slider' },
      {
        key: 'coinsBanner',
        type: 'group',
        label: 'Rosier Coins banner',
        fields: [
          { key: 'title', type: 'textarea', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Text' },
          { key: 'button', type: 'text', label: 'Button text' },
        ],
      },
      {
        key: 'heroSource',
        type: 'select',
        label: 'Top slider shows',
        options: [
          { value: 'website', label: 'Live banners from rosierfoods.com (my banners below when offline)' },
          { value: 'custom', label: 'Only my banners below' },
          { value: 'both', label: 'My banners first, then the website banners' },
        ],
      },
      {
        key: 'heroBanners',
        type: 'list',
        label: 'My slider banners',
        itemLabel: '{title}',
        newItem: { enabled: true, kind: 'image', image: '', title: '', sub: '', colors: ['#FFF3D6', '#E9B955'], light: false, link: '', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this banner' },
          {
            key: 'kind',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'image', label: 'Just my image (designed banner)' },
              { value: 'card', label: 'Colour card with title + floating product photo' },
            ],
          },
          { key: 'image', type: 'image', label: 'Image', help: 'For "Just my image", use a wide banner around 1000 × 800 px.' },
          { key: 'title', type: 'textarea', label: 'Title', showIf: { kind: ['card'] } },
          { key: 'sub', type: 'textarea', label: 'Text', showIf: { kind: ['card'] } },
          { key: 'colors', type: 'colors', label: 'Card gradient', showIf: { kind: ['card'] } },
          { key: 'light', type: 'boolean', label: 'Light text (for dark cards)', showIf: { kind: ['card'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
          ...schedule,
        ],
      },
      {
        key: 'tilesSource',
        type: 'select',
        label: 'Two tiles under the slider',
        options: [
          { value: 'website', label: 'Live from rosierfoods.com' },
          { value: 'custom', label: 'My tiles below' },
          { value: 'none', label: 'Hide' },
        ],
      },
      {
        key: 'tiles',
        type: 'list',
        label: 'My tiles',
        itemLabel: '{link}',
        max: 2,
        newItem: { image: '', link: '' },
        fields: [
          { key: 'image', type: 'image', label: 'Image', help: 'Around 700 × 385 px.' },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
        ],
      },
      {
        key: 'sections',
        type: 'list',
        label: 'Sections (drag to reorder)',
        itemLabel: '{title|type}',
        newItem: { type: 'image', enabled: true, title: '', image: '', link: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this section' },
          { key: 'type', type: 'select', label: 'Section type', options: SECTION_TYPES },
          { key: 'title', type: 'text', label: 'Title', showIf: { type: ['categories', 'deals', 'grid', 'row', 'promo', 'reviews'] } },
          { key: 'subtitle', type: 'text', label: 'Subtitle', showIf: { type: ['grid', 'reviews'] } },
          { key: 'handles', type: 'products', label: 'Products', help: 'Leave empty to fill automatically (deals: biggest discounts; grid/row: the category below).', showIf: { type: ['deals', 'grid', 'row'] } },
          { key: 'category', type: 'category', label: 'Or show a category', showIf: { type: ['grid', 'row'] } },
          { key: 'limit', type: 'number', label: 'How many products', showIf: { type: ['grid'] } },
          { key: 'showViewAll', type: 'boolean', label: 'Show "View all" button', showIf: { type: ['grid'] } },
          { key: 'kicker', type: 'text', label: 'Small text above title', showIf: { type: ['promo'] } },
          { key: 'body', type: 'textarea', label: 'Text', showIf: { type: ['promo'] } },
          { key: 'button', type: 'text', label: 'Button text', showIf: { type: ['promo'] } },
          { key: 'image', type: 'image', label: 'Image', showIf: { type: ['promo', 'image'] } },
          { key: 'colors', type: 'colors', label: 'Background gradient', showIf: { type: ['promo'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP, showIf: { type: ['promo', 'image', 'row'] } },
          { key: 'height', type: 'number', label: 'Height in the app (0 = keep the image’s own shape)', showIf: { type: ['image'] } },
          { key: 'bg', type: 'color', label: 'Section background colour', help: 'Leave empty for none.' },
          { key: 'titleColor', type: 'color', label: 'Title colour', help: 'Leave empty to use the theme colour.', showIf: { type: ['categories', 'deals', 'grid', 'row', 'reviews'] } },
          { key: 'titleSize', type: 'number', label: 'Title size (px)', help: '0 = normal.', showIf: { type: ['categories', 'deals', 'grid', 'row', 'reviews'] } },
          { key: 'spaceAbove', type: 'number', label: 'Extra space above (px)', help: 'Can be negative to pull it closer.' },
          { key: 'spaceBelow', type: 'number', label: 'Extra space below (px)' },
          {
            key: 'animation',
            type: 'select',
            label: 'Entrance animation',
            options: [
              { value: '', label: 'Default' },
              { value: 'fadeUp', label: 'Fade up' },
              { value: 'fadeDown', label: 'Fade down' },
              { value: 'fade', label: 'Fade in' },
              { value: 'zoom', label: 'Zoom in' },
              { value: 'slideLeft', label: 'Slide in from the right' },
              { value: 'slideRight', label: 'Slide in from the left' },
              { value: 'none', label: 'None' },
            ],
          },
          { key: 'animSpeed', type: 'number', label: 'Animation speed (× normal)', help: '1 = normal, 2 = twice as fast, 0.5 = slower.' },
        ],
      },
    ],
  },
  {
    key: 'categories',
    title: 'Categories',
    icon: 'shape-outline',
    description: 'Names, order and pictures of the shop categories.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Categories (drag to reorder)',
        itemLabel: '{label}',
        newItem: { id: '', enabled: true, label: '', icon: 'combo', image: '', blurb: '', tint: '#F4E1C4' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show' },
          { key: 'id', type: 'text', label: 'Category ID', help: 'Products are matched to categories by this ID (ghee, atta, oils, breakfast, immunity, pickles, combos). Assign products to a new ID under Products.' },
          { key: 'label', type: 'text', label: 'Name' },
          { key: 'blurb', type: 'text', label: 'One-line description' },
          {
            key: 'icon',
            type: 'select',
            label: 'Built-in icon',
            options: ['ghee', 'atta', 'oil', 'breakfast', 'immunity', 'pickle', 'combo'].map((v) => ({ value: v, label: v })),
          },
          { key: 'image', type: 'image', label: 'Or your own icon image', help: 'Square PNG with a transparent background works best.' },
          { key: 'tint', type: 'color', label: 'Header colour' },
        ],
      },
    ],
  },
  {
    key: 'products',
    title: 'Products',
    icon: 'basket-outline',
    description: 'Products and prices come live from Shopify. Here you can hide a product in the app or change its badge, category or rating.',
    fields: [
      {
        key: 'overrides',
        type: 'list',
        label: 'Product changes',
        itemLabel: '{handle}',
        newItem: { handle: '', hidden: false, badge: '', category: '', rating: 0, title: '', image: '' },
        fields: [
          { key: 'handle', type: 'product', label: 'Product' },
          { key: 'hidden', type: 'boolean', label: 'Hide from the app' },
          { key: 'title', type: 'text', label: 'Name in the app', help: 'Leave empty to use the Shopify name.' },
          { key: 'badge', type: 'text', label: 'Badge', help: 'e.g. 🔥 Bestseller. Leave empty to keep the current one.' },
          { key: 'category', type: 'category', label: 'Category' },
          { key: 'rating', type: 'number', label: 'Star rating', help: '0 = keep current.' },
          { key: 'image', type: 'image', label: 'Main photo in the app', help: 'Leave empty to use the Shopify photo.' },
        ],
      },
    ],
  },
  {
    key: 'coins',
    title: 'Rosier Coins',
    icon: 'database-outline',
    description: 'Earning rules, vouchers and everything on the Coins screen.',
    fields: [
      { key: 'earnPerRupee', type: 'number', label: 'Coins per ₹1', help: '0.05 = 5 coins for every ₹100.' },
      { key: 'welcomeBonus', type: 'number', label: 'Welcome coins' },
      { key: 'reviewBonus', type: 'number', label: 'Coins for a review' },
      { key: 'referralBonus', type: 'number', label: 'Coins for a referral' },
      { key: 'pendingDays', type: 'number', label: 'Days until coins unlock' },
      { key: 'minCartForVoucher', type: 'number', label: 'Minimum cart (₹) to use a voucher' },
      {
        key: 'vouchers',
        type: 'list',
        label: 'Vouchers',
        itemLabel: '₹{value} for {cost} coins',
        newItem: { id: '', value: 100, cost: 500, code: '', tint: 'brown' },
        fields: [
          { key: 'id', type: 'text', label: 'ID', help: 'Short unique ID, e.g. v100.' },
          { key: 'value', type: 'number', label: 'Discount (₹)' },
          { key: 'cost', type: 'number', label: 'Cost in coins' },
          { key: 'code', type: 'text', label: 'Shopify discount code', help: 'Must exist in Shopify → Discounts.' },
          {
            key: 'tint',
            type: 'select',
            label: 'Colour',
            options: ['copper', 'brown', 'green', 'deep'].map((v) => ({ value: v, label: v })),
          },
        ],
      },
      { key: 'referralMessage', type: 'textarea', label: 'Refer-a-friend share message' },
      {
        key: 'steps',
        type: 'list',
        label: 'How coins work (timeline)',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'promoTitle', type: 'textarea', label: 'Bottom banner title' },
      { key: 'promoBody', type: 'text', label: 'Bottom banner text' },
      { key: 'promoButton', type: 'text', label: 'Bottom banner button' },
      faq('FAQs'),
    ],
  },
  {
    key: 'benefits',
    title: 'Benefits Club',
    icon: 'crown-outline',
    description: 'The gold banner on home and the Benefits Club page.',
    fields: [
      { key: 'bannerTitle', type: 'text', label: 'Banner title' },
      { key: 'bannerSubtitle', type: 'text', label: 'Banner subtitle' },
      { key: 'bannerTagline', type: 'text', label: 'Banner tagline' },
      {
        key: 'bannerPerks',
        type: 'list',
        label: 'Banner perks (5 fit best)',
        itemLabel: '{label}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'label', type: 'textarea', label: 'Label' },
        ],
      },
      { key: 'pageTitle', type: 'text', label: 'Page title' },
      { key: 'pageSubtitle', type: 'text', label: 'Page subtitle' },
      { key: 'cardFooter', type: 'text', label: 'Text on the member card' },
      {
        key: 'perks',
        type: 'list',
        label: 'Page perks',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'plansTitle', type: 'text', label: 'Plans heading' },
      { key: 'popularPlanMonths', type: 'number', label: 'Plan marked POPULAR (months)' },
      { key: 'membershipHandle', type: 'product', label: 'Membership product' },
    ],
  },
  {
    key: 'reviews',
    title: 'Reviews',
    icon: 'star-outline',
    description: 'Customer reviews on the home screen.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Reviews',
        itemLabel: '{name} — {title}',
        newItem: { title: '', body: '', name: '', product: '', rating: 5, photo: '' },
        fields: [
          { key: 'title', type: 'text', label: 'Headline' },
          { key: 'body', type: 'textarea', label: 'Review' },
          { key: 'name', type: 'text', label: 'Customer name' },
          { key: 'product', type: 'text', label: 'Product name' },
          { key: 'rating', type: 'number', label: 'Stars (1–5)' },
          { key: 'photo', type: 'image', label: 'Customer photo (optional)' },
        ],
      },
    ],
  },
  {
    key: 'pillars',
    title: 'Rosier experience',
    icon: 'sprout-outline',
    description: 'The four pillars on home and Our Story.',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'subtitle', type: 'text', label: 'Subtitle' },
      {
        key: 'items',
        type: 'list',
        label: 'Pillars',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
    ],
  },
  {
    key: 'account',
    title: 'Login & account',
    icon: 'account-key-outline',
    description: 'Text on the login screen and the login prompts. Switch login on under Shopify connection.',
    fields: [
      { key: 'loginTitle', type: 'text', label: 'Login screen title' },
      { key: 'loginBody', type: 'textarea', label: 'Login screen text' },
      { key: 'loginButton', type: 'text', label: 'Login button' },
      { key: 'skipLabel', type: 'text', label: '"Not now" button' },
      {
        key: 'perks',
        type: 'list',
        label: 'Reasons to log in',
        itemLabel: '{text}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'text', type: 'text', label: 'Text' },
        ],
      },
      { key: 'checkoutPromptTitle', type: 'text', label: 'Checkout prompt title', help: 'Shown when someone taps Checkout without logging in.' },
      { key: 'checkoutPromptBody', type: 'textarea', label: 'Checkout prompt text' },
      { key: 'guestLabel', type: 'text', label: '"Continue as guest" button' },
      { key: 'profileCardTitle', type: 'text', label: 'Profile tab: login card title' },
      { key: 'profileCardBody', type: 'text', label: 'Profile tab: login card text' },
      { key: 'ordersLoginPrompt', type: 'text', label: 'Orders screen: login prompt' },
    ],
  },
  {
    key: 'announcements',
    title: 'Notifications',
    icon: 'bell-outline',
    description: 'Messages that land in every user’s notification inbox in the app (with a red badge) the next time they open it.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Messages',
        itemLabel: '{title}',
        newItem: { id: '', title: '', body: '', link: '' },
        autoId: true,
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
          { key: 'link', type: 'link', label: 'Opens when tapped (optional)', help: LINK_HELP },
        ],
      },
    ],
  },
  {
    key: 'about',
    title: 'Our Story',
    icon: 'book-open-page-variant-outline',
    fields: [
      { key: 'heroImage', type: 'image', label: 'Top image (optional)' },
      { key: 'headline', type: 'textarea', label: 'Headline' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      {
        key: 'blocks',
        type: 'list',
        label: 'Blocks',
        itemLabel: '{title}',
        newItem: { type: 'text', title: '', body: '', signature: '', image: '' },
        fields: [
          {
            key: 'type',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'text', label: 'Heading + text' },
              { value: 'quote', label: 'Quote card' },
            ],
          },
          { key: 'title', type: 'text', label: 'Heading' },
          { key: 'body', type: 'textarea', label: 'Text', help: 'Leave a blank line between paragraphs.' },
          { key: 'signature', type: 'text', label: 'Signature', showIf: { type: ['quote'] } },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      { key: 'labReportsPath', type: 'text', label: 'Lab reports page on the website' },
      { key: 'websitePath', type: 'text', label: 'About page on the website' },
    ],
  },
  {
    key: 'blog',
    title: 'Blog',
    icon: 'newspaper-variant-outline',
    fields: [
      {
        key: 'articles',
        type: 'list',
        label: 'Articles',
        itemLabel: '{title}',
        autoId: true,
        newItem: { id: '', enabled: true, title: '', kicker: '', mins: 2, icon: 'leaf', colors: ['#F6D98C', '#C98A52'], image: '', product: '', body: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Published' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'kicker', type: 'text', label: 'Tag (e.g. Tradition)' },
          { key: 'mins', type: 'number', label: 'Minutes to read' },
          { key: 'image', type: 'image', label: 'Cover image', help: 'If empty, the icon on a colour gradient is used.' },
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'colors', type: 'colors', label: 'Cover gradient' },
          { key: 'body', type: 'textarea', label: 'Article', rows: 12, help: 'Leave a blank line between paragraphs.' },
          { key: 'product', type: 'product', label: '"Shop the product" button' },
        ],
      },
    ],
  },
  {
    key: 'gifting',
    title: 'Gifting',
    icon: 'gift-outline',
    fields: [
      { key: 'image', type: 'image', label: 'Header image (optional)' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'email', type: 'text', label: 'Enquiry email' },
      { key: 'subject', type: 'text', label: 'Email subject' },
      { key: 'category', type: 'category', label: 'Products shown' },
    ],
  },
  {
    key: 'help',
    title: 'Help & Support',
    icon: 'lifebuoy',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      { key: 'phone', type: 'text', label: 'Phone (with +91)' },
      { key: 'phoneLabel', type: 'text', label: 'Phone as shown' },
      { key: 'email', type: 'text', label: 'Email' },
      { key: 'contactPath', type: 'text', label: 'Contact page on the website' },
      faq('FAQs'),
      { key: 'company', type: 'text', label: 'Company name' },
      { key: 'address', type: 'textarea', label: 'Address' },
    ],
  },
  {
    key: 'coupons',
    title: 'Coupons',
    icon: 'ticket-percent-outline',
    description: 'The coupon box in the cart and the list of offers customers can tap to apply. Create the actual discount codes in Shopify → Discounts — the app checks every code with Shopify before checkout.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show the coupon box in the cart' },
      { key: 'boxTitle', type: 'text', label: 'Coupon box title' },
      { key: 'placeholder', type: 'text', label: 'Hint inside the box' },
      { key: 'showList', type: 'boolean', label: 'Show “Available coupons” list' },
      { key: 'listTitle', type: 'text', label: 'List title' },
      {
        key: 'items',
        type: 'list',
        label: 'Coupons shown to customers',
        help: 'Use “Import from Shopify” to fill this from your Shopify discounts. Codes not listed here still work if typed in.',
        itemLabel: '{code} — {title}',
        newItem: { enabled: true, code: '', title: '', description: '', kind: 'percent', value: 10, minOrder: 0, maxDiscount: 0, startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this coupon' },
          { key: 'code', type: 'text', label: 'Code', help: 'Exactly as created in Shopify → Discounts.' },
          { key: 'title', type: 'text', label: 'Headline', help: 'e.g. Flat ₹100 off on ₹999+' },
          { key: 'description', type: 'textarea', label: 'Details / terms' },
          {
            key: 'kind',
            type: 'select',
            label: 'Discount type',
            help: 'Used to show the saving before Shopify confirms it.',
            options: [
              { value: 'percent', label: '% off' },
              { value: 'flat', label: '₹ off' },
              { value: 'freeship', label: 'Free shipping' },
              { value: 'other', label: 'Other (buy X get Y, gift…)' },
            ],
          },
          { key: 'value', type: 'number', label: 'Amount (% or ₹)', showIf: { kind: ['percent', 'flat'] } },
          { key: 'minOrder', type: 'number', label: 'Minimum order (₹)', help: '0 = no minimum.' },
          { key: 'maxDiscount', type: 'number', label: 'Maximum discount (₹)', help: '0 = no cap.', showIf: { kind: ['percent'] } },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'tracking',
    title: 'Order tracking',
    icon: 'truck-fast-outline',
    description: 'The “Track order” screen. Logged-in customers see live courier status on each order; anyone can track with order number + email/phone (needs the Admin API connected).',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show “Track order” in the app' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      { key: 'orderLabel', type: 'text', label: 'Order number label' },
      { key: 'contactLabel', type: 'text', label: 'Email / phone label' },
      { key: 'help', type: 'textarea', label: 'Note under the tracking timeline' },
      { key: 'websiteTrackUrl', type: 'text', label: 'Courier tracking page (optional)', help: 'Used when Shopify has a tracking number but no link. Put {number} where the tracking number goes, e.g. https://shiprocket.co/tracking/{number}' },
      {
        key: 'steps',
        type: 'group',
        label: 'Timeline step names',
        fields: [
          { key: 'ordered', type: 'text', label: 'Step 1' },
          { key: 'confirmed', type: 'text', label: 'Step 2' },
          { key: 'shipped', type: 'text', label: 'Step 3' },
          { key: 'out', type: 'text', label: 'Step 4' },
          { key: 'delivered', type: 'text', label: 'Step 5' },
        ],
      },
    ],
  },
  {
    key: 'search',
    title: 'Search',
    icon: 'magnify',
    fields: [{ key: 'popular', type: 'strings', label: 'Popular searches' }],
  },
  {
    key: 'effects',
    title: 'Seasonal effects',
    icon: 'snowflake',
    description: 'Snow for winter, sparkles for Diwali, colours for Holi… Falls gently over the app without blocking taps. Turn it on, pick an effect, publish.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Show seasonal effects in the app', help: 'The main on/off switch. Off = no effects anywhere.' },
      { key: 'userToggle', type: 'boolean', label: 'Let customers turn effects off in their Profile' },
      {
        key: 'items',
        type: 'list',
        label: 'Effects',
        help: 'The first effect in this list that is switched on (and inside its dates) is the one shown. Set dates to run one automatically, e.g. snow from 1 Dec to 31 Jan.',
        itemLabel: '{name}',
        newItem: { enabled: true, name: 'New effect', type: 'snow', amount: 40, speed: 1, size: 1, opacity: 0.9, colors: [], emoji: '', image: '', screens: 'home', stopAfter: 0, startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Switched on' },
          { key: 'name', type: 'text', label: 'Name (only you see this)' },
          {
            key: 'type',
            type: 'select',
            label: 'Effect',
            options: [
              { value: 'snow', label: '❄️ Snowfall (winter / Christmas)' },
              { value: 'sparkles', label: '✨ Golden sparkles (Diwali)' },
              { value: 'diyas', label: '🪔 Floating diyas (Diwali)' },
              { value: 'holi', label: '🎨 Holi colours' },
              { value: 'rain', label: '🌧️ Rain (monsoon)' },
              { value: 'confetti', label: '🎉 Confetti (sale / celebration)' },
              { value: 'petals', label: '🌸 Falling petals (spring / wedding season)' },
              { value: 'hearts', label: '💛 Hearts (Valentine’s / Mother’s Day)' },
              { value: 'leaves', label: '🍂 Autumn leaves' },
              { value: 'kites', label: '🪁 Kites (Sankranti)' },
              { value: 'emoji', label: 'Your own emoji' },
              { value: 'image', label: 'Your own image' },
            ],
          },
          { key: 'emoji', type: 'text', label: 'Emoji to use', help: 'One or more, separated by spaces, e.g. 🥭 🌞', showIf: { type: ['emoji'] } },
          { key: 'image', type: 'image', label: 'Image to use', help: 'A small PNG with a transparent background works best (e.g. a coin, a flower).', showIf: { type: ['image'] } },
          { key: 'amount', type: 'number', label: 'How many at once', help: '10 = a few, 40 = normal, 80 = heavy.' },
          { key: 'speed', type: 'number', label: 'Speed (× normal)', help: '1 = normal, 0.5 = slow and dreamy, 2 = fast.' },
          { key: 'size', type: 'number', label: 'Size (× normal)', help: '1 = normal.' },
          { key: 'opacity', type: 'number', label: 'Strength (0–1)', help: '1 = fully visible, 0.5 = subtle.' },
          { key: 'colors', type: 'colors', label: 'Colours', help: 'Leave empty for the effect’s own colours.', showIf: { type: ['snow', 'sparkles', 'holi', 'rain', 'confetti', 'petals', 'hearts'] } },
          {
            key: 'screens',
            type: 'select',
            label: 'Where it shows',
            options: [
              { value: 'home', label: 'Home screen only' },
              { value: 'tabs', label: 'Main tabs (Home, Shop, Coins, Cart, Profile)' },
              { value: 'all', label: 'Every screen' },
            ],
          },
          { key: 'stopAfter', type: 'number', label: 'Stop after (seconds)', help: '0 = keeps going. 8 = a short burst each time the app opens.' },
          ...schedule,
        ],
      },
    ],
  },
  {
    key: 'theme',
    title: 'Theme & sizes',
    icon: 'palette-outline',
    description: 'Colours and sizes across the app. Watch the phone on the right while you change them.',
    fields: [
      {
        key: 'light',
        type: 'group',
        label: 'Colours — light mode',
        fields: [
          { key: 'bg', type: 'color', label: 'Page background' },
          { key: 'header', type: 'color', label: 'Top bar background' },
          { key: 'card', type: 'color', label: 'Soft card / tile background' },
          { key: 'cardStrong', type: 'color', label: 'White card background' },
          { key: 'border', type: 'color', label: 'Lines & borders' },
          { key: 'text', type: 'color', label: 'Main text' },
          { key: 'textSoft', type: 'color', label: 'Secondary text' },
          { key: 'textMute', type: 'color', label: 'Faint text (hints, placeholders)' },
          { key: 'heading', type: 'color', label: 'Headings' },
          { key: 'primary', type: 'color', label: 'Brand colour (buttons, links)' },
          { key: 'accent', type: 'color', label: 'Accent' },
          { key: 'deepAlt', type: 'color', label: 'Dark brown (badges, buttons)' },
          { key: 'gold', type: 'color', label: 'Gold (coins, stars)' },
          { key: 'price', type: 'color', label: 'Price colour' },
          { key: 'green', type: 'color', label: 'Discount / success green' },
          { key: 'tabBar', type: 'color', label: 'Bottom tab bar' },
        ],
      },
      {
        key: 'dark',
        type: 'group',
        label: 'Colours — dark mode',
        fields: [
          { key: 'bg', type: 'color', label: 'Page background' },
          { key: 'header', type: 'color', label: 'Top bar background' },
          { key: 'card', type: 'color', label: 'Soft card / tile background' },
          { key: 'cardStrong', type: 'color', label: 'White card background' },
          { key: 'border', type: 'color', label: 'Lines & borders' },
          { key: 'text', type: 'color', label: 'Main text' },
          { key: 'textSoft', type: 'color', label: 'Secondary text' },
          { key: 'textMute', type: 'color', label: 'Faint text (hints, placeholders)' },
          { key: 'heading', type: 'color', label: 'Headings' },
          { key: 'primary', type: 'color', label: 'Brand colour (buttons, links)' },
          { key: 'accent', type: 'color', label: 'Accent' },
          { key: 'deepAlt', type: 'color', label: 'Dark brown (badges, buttons)' },
          { key: 'gold', type: 'color', label: 'Gold (coins, stars)' },
          { key: 'price', type: 'color', label: 'Price colour' },
          { key: 'green', type: 'color', label: 'Discount / success green' },
          { key: 'tabBar', type: 'color', label: 'Bottom tab bar' },
        ],
      },
      {
        key: 'layout',
        type: 'group',
        label: 'Sizes',
        fields: [
          { key: 'heroCardHeight', type: 'number', label: 'Top slider: colour card height (px)', help: 'Default 212. Used when the slider shows colour cards, not images.' },
          { key: 'heroImageRatio', type: 'number', label: 'Top slider: image shape (width ÷ height)', help: '0 = automatic (matches your banner images). 1.25 = slightly wide, 1 = square, 2 = wide strip.' },
          { key: 'heroRadius', type: 'number', label: 'Top slider: corner roundness', help: 'Default 22. 0 = sharp corners.' },
          { key: 'carouselSeconds', type: 'number', label: 'Top slider: seconds per slide', help: 'Default 4.2. 0 = don’t auto-slide.' },
          { key: 'tileRatio', type: 'number', label: 'Tiles under the slider: height ÷ width', help: 'Default 0.55.' },
          { key: 'tileRadius', type: 'number', label: 'Tiles: corner roundness', help: 'Default 16.' },
          { key: 'categoryTile', type: 'number', label: 'Category tile width (px)', help: 'Default 72.' },
          { key: 'categoryIcon', type: 'number', label: 'Category icon size (px)', help: 'Default 44.' },
          { key: 'dealCardWidth', type: 'number', label: 'Deal card width (px)', help: 'Default 160 — the cards in sideways rows.' },
          { key: 'productImageRatio', type: 'number', label: 'Product photo height (× card width)', help: 'Default 0.9. Bigger = taller photos.' },
          { key: 'cardRadius', type: 'number', label: 'Product card corner roundness', help: 'Default 20.' },
          { key: 'imageBannerRadius', type: 'number', label: 'Image banners: corner roundness', help: 'Default 18.' },
          { key: 'sectionSpacing', type: 'number', label: 'Space between home sections (× normal)', help: 'Default 1. 0.5 = tighter, 1.5 = more air.' },
        ],
      },
    ],
  },
  {
    key: 'general',
    title: 'App settings',
    icon: 'cog-outline',
    description: 'Logo, maintenance mode and forcing users to update.',
    fields: [
      { key: 'logo', type: 'image', label: 'Logo', help: 'Black logo on a transparent background — the app recolours it.' },
      { key: 'tagline', type: 'text', label: 'Tagline' },
      { key: 'footerNote', type: 'text', label: 'Home footer line' },
      {
        key: 'welcomeNotification',
        type: 'group',
        label: 'First notification new users get',
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
        ],
      },
      {
        key: 'maintenance',
        type: 'group',
        label: 'Maintenance mode',
        fields: [
          { key: 'enabled', type: 'boolean', label: 'App is in maintenance (blocks the whole app)' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      {
        key: 'update',
        type: 'group',
        label: 'App update prompt',
        fields: [
          { key: 'minVersion', type: 'text', label: 'Minimum app version', help: 'People on an older version see the update prompt. Current app version is 1.0.0.' },
          { key: 'force', type: 'boolean', label: 'Block the app until they update' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'androidUrl', type: 'text', label: 'Play Store link' },
          { key: 'iosUrl', type: 'text', label: 'App Store link' },
        ],
      },
    ],
  },
];

export const SECTION_KEYS = SCHEMA.map((s) => s.key);
