/**
 * Describes every editable section of the app for the admin panel.
 * The admin panel renders its forms from this file, so adding a field here
 * (and reading it in the app) is all it takes to make something editable.
 *
 * Field types:
 *  text, textarea, number, boolean, color, image, images, link, icon,
 *  select (options), datetime, product, products, category, colors,
 *  list (of `fields`), group (of `fields`), strings (list of short texts)
 */

const LINK_HELP = 'A product (/products/handle), a collection (/collections/ghee), an app screen (app:/coins) or any https:// link.';
const ICON_HELP = 'Any Material Design icon name, e.g. gift-outline. Browse them at pictogrammers.com/library/mdi';

const schedule = [
  { key: 'startAt', type: 'datetime', label: 'Show from', help: 'Leave empty to show right away.' },
  { key: 'endAt', type: 'datetime', label: 'Show until', help: 'Leave empty to keep showing.' },
];

const faq = (label = 'Questions') => ({
  key: 'faq',
  type: 'list',
  label,
  itemLabel: '{q}',
  fields: [
    { key: 'q', type: 'text', label: 'Question' },
    { key: 'a', type: 'textarea', label: 'Answer', help: 'You can use {per100}, {pendingDays}, {welcomeBonus}.' },
  ],
});

const SECTION_TYPES = [
  { value: 'categories', label: 'Category icons' },
  { value: 'deals', label: 'Deals row (biggest discounts)' },
  { value: 'benefits', label: 'Benefits Club banner' },
  { value: 'grid', label: 'Product grid' },
  { value: 'row', label: 'Product row (scrolls sideways)' },
  { value: 'promo', label: 'Promo strip (image + text)' },
  { value: 'image', label: 'Full-width image banner' },
  { value: 'reviews', label: 'Customer reviews' },
  { value: 'pillars', label: 'Rosier experience (4 pillars)' },
];

export const SCHEMA = [
  {
    key: 'onboarding',
    title: 'Intro slides',
    icon: 'presentation-play',
    description: 'The slides people see the first time they open the app. Raise "Show again version" to show them to everyone once more.',
    fields: [
      { key: 'reshowVersion', type: 'number', label: 'Show again version', help: 'Increase by 1 and publish: every user sees the intro slides again on their next app open.' },
      { key: 'background', type: 'color', label: 'Background colour' },
      { key: 'accent', type: 'color', label: 'Title colour' },
      { key: 'skipLabel', type: 'text', label: 'Skip button text' },
      { key: 'buttonLabel', type: 'text', label: 'Last button text' },
      { key: 'namePlaceholder', type: 'text', label: 'Name box placeholder' },
      { key: 'welcomeNote', type: 'text', label: 'Welcome coins note', help: '{welcomeBonus} becomes the welcome coin amount.' },
      {
        key: 'slides',
        type: 'list',
        label: 'Slides',
        itemLabel: '{title}',
        newItem: { enabled: true, art: 'image', showLogo: false, title: 'NEW SLIDE', sub: '', image: '', images: [], chips: [], showNameInput: false },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this slide' },
          {
            key: 'art',
            type: 'select',
            label: 'Animation',
            options: [
              { value: 'collage', label: 'Floating photo collage (up to 7 photos)' },
              { value: 'churn', label: 'Spinning rings around one photo' },
              { value: 'coins', label: 'Falling Rosier coins' },
              { value: 'image', label: 'One big floating image' },
            ],
          },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'sub', type: 'textarea', label: 'Text' },
          { key: 'showLogo', type: 'boolean', label: 'Show Rosier logo above title' },
          { key: 'image', type: 'image', label: 'Main image', showIf: { art: ['churn', 'image'] } },
          { key: 'images', type: 'images', label: 'Collage photos', max: 7, showIf: { art: ['collage'] } },
          {
            key: 'chips',
            type: 'list',
            label: 'Step chips under the text',
            itemLabel: '{label}',
            fields: [
              { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
              { key: 'label', type: 'text', label: 'Label' },
            ],
          },
          { key: 'showNameInput', type: 'boolean', label: 'Ask for their name (+ photo) on this slide' },
        ],
      },
    ],
  },
  {
    key: 'popup',
    title: 'Launch popup',
    icon: 'message-image-outline',
    description: 'An offer or announcement that pops up when the app opens.',
    fields: [
      { key: 'enabled', type: 'boolean', label: 'Popup is on' },
      { key: 'id', type: 'text', label: 'Popup ID', help: 'Change this to show a new popup to people who already closed the old one.' },
      {
        key: 'frequency',
        type: 'select',
        label: 'How often',
        options: [
          { value: 'once', label: 'Once per person' },
          { value: 'daily', label: 'Once a day' },
          { value: 'every_launch', label: 'Every time the app opens' },
        ],
      },
      { key: 'image', type: 'image', label: 'Image' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'link', type: 'link', label: 'Button opens', help: LINK_HELP },
      ...schedule,
    ],
  },
  {
    key: 'home',
    title: 'Home screen',
    icon: 'home-outline',
    description: 'Banners and the order of every section on the home screen.',
    fields: [
      { key: 'searchPlaceholder', type: 'text', label: 'Search bar text' },
      { key: 'showCoinsBanner', type: 'boolean', label: 'Show the Rosier Coins banner first in the slider' },
      {
        key: 'coinsBanner',
        type: 'group',
        label: 'Rosier Coins banner',
        fields: [
          { key: 'title', type: 'textarea', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Text' },
          { key: 'button', type: 'text', label: 'Button text' },
        ],
      },
      {
        key: 'heroSource',
        type: 'select',
        label: 'Top slider shows',
        options: [
          { value: 'website', label: 'Live banners from rosierfoods.com (my banners below when offline)' },
          { value: 'custom', label: 'Only my banners below' },
          { value: 'both', label: 'My banners first, then the website banners' },
        ],
      },
      {
        key: 'heroBanners',
        type: 'list',
        label: 'My slider banners',
        itemLabel: '{title}',
        newItem: { enabled: true, kind: 'image', image: '', title: '', sub: '', colors: ['#FFF3D6', '#E9B955'], light: false, link: '', startAt: '', endAt: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this banner' },
          {
            key: 'kind',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'image', label: 'Just my image (designed banner)' },
              { value: 'card', label: 'Colour card with title + floating product photo' },
            ],
          },
          { key: 'image', type: 'image', label: 'Image', help: 'For "Just my image", use a wide banner around 1000 × 800 px.' },
          { key: 'title', type: 'textarea', label: 'Title', showIf: { kind: ['card'] } },
          { key: 'sub', type: 'textarea', label: 'Text', showIf: { kind: ['card'] } },
          { key: 'colors', type: 'colors', label: 'Card gradient', showIf: { kind: ['card'] } },
          { key: 'light', type: 'boolean', label: 'Light text (for dark cards)', showIf: { kind: ['card'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
          ...schedule,
        ],
      },
      {
        key: 'tilesSource',
        type: 'select',
        label: 'Two tiles under the slider',
        options: [
          { value: 'website', label: 'Live from rosierfoods.com' },
          { value: 'custom', label: 'My tiles below' },
          { value: 'none', label: 'Hide' },
        ],
      },
      {
        key: 'tiles',
        type: 'list',
        label: 'My tiles',
        itemLabel: '{link}',
        max: 2,
        newItem: { image: '', link: '' },
        fields: [
          { key: 'image', type: 'image', label: 'Image', help: 'Around 700 × 385 px.' },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP },
        ],
      },
      {
        key: 'sections',
        type: 'list',
        label: 'Sections (drag to reorder)',
        itemLabel: '{title|type}',
        newItem: { type: 'image', enabled: true, title: '', image: '', link: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show this section' },
          { key: 'type', type: 'select', label: 'Section type', options: SECTION_TYPES },
          { key: 'title', type: 'text', label: 'Title', showIf: { type: ['categories', 'deals', 'grid', 'row', 'promo', 'reviews'] } },
          { key: 'subtitle', type: 'text', label: 'Subtitle', showIf: { type: ['grid', 'reviews'] } },
          { key: 'handles', type: 'products', label: 'Products', help: 'Leave empty to fill automatically (deals: biggest discounts; grid/row: the category below).', showIf: { type: ['deals', 'grid', 'row'] } },
          { key: 'category', type: 'category', label: 'Or show a category', showIf: { type: ['grid', 'row'] } },
          { key: 'limit', type: 'number', label: 'How many products', showIf: { type: ['grid'] } },
          { key: 'showViewAll', type: 'boolean', label: 'Show "View all" button', showIf: { type: ['grid'] } },
          { key: 'kicker', type: 'text', label: 'Small text above title', showIf: { type: ['promo'] } },
          { key: 'body', type: 'textarea', label: 'Text', showIf: { type: ['promo'] } },
          { key: 'button', type: 'text', label: 'Button text', showIf: { type: ['promo'] } },
          { key: 'image', type: 'image', label: 'Image', showIf: { type: ['promo', 'image'] } },
          { key: 'colors', type: 'colors', label: 'Background gradient', showIf: { type: ['promo'] } },
          { key: 'link', type: 'link', label: 'Opens', help: LINK_HELP, showIf: { type: ['promo', 'image', 'row'] } },
        ],
      },
    ],
  },
  {
    key: 'categories',
    title: 'Categories',
    icon: 'shape-outline',
    description: 'Names, order and pictures of the shop categories.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Categories (drag to reorder)',
        itemLabel: '{label}',
        newItem: { id: '', enabled: true, label: '', icon: 'combo', image: '', blurb: '', tint: '#F4E1C4' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Show' },
          { key: 'id', type: 'text', label: 'Category ID', help: 'Products are matched to categories by this ID (ghee, atta, oils, breakfast, immunity, pickles, combos). Assign products to a new ID under Products.' },
          { key: 'label', type: 'text', label: 'Name' },
          { key: 'blurb', type: 'text', label: 'One-line description' },
          {
            key: 'icon',
            type: 'select',
            label: 'Built-in icon',
            options: ['ghee', 'atta', 'oil', 'breakfast', 'immunity', 'pickle', 'combo'].map((v) => ({ value: v, label: v })),
          },
          { key: 'image', type: 'image', label: 'Or your own icon image', help: 'Square PNG with a transparent background works best.' },
          { key: 'tint', type: 'color', label: 'Header colour' },
        ],
      },
    ],
  },
  {
    key: 'products',
    title: 'Products',
    icon: 'basket-outline',
    description: 'Products and prices come live from Shopify. Here you can hide a product in the app or change its badge, category or rating.',
    fields: [
      {
        key: 'overrides',
        type: 'list',
        label: 'Product changes',
        itemLabel: '{handle}',
        newItem: { handle: '', hidden: false, badge: '', category: '', rating: 0, title: '', image: '' },
        fields: [
          { key: 'handle', type: 'product', label: 'Product' },
          { key: 'hidden', type: 'boolean', label: 'Hide from the app' },
          { key: 'title', type: 'text', label: 'Name in the app', help: 'Leave empty to use the Shopify name.' },
          { key: 'badge', type: 'text', label: 'Badge', help: 'e.g. 🔥 Bestseller. Leave empty to keep the current one.' },
          { key: 'category', type: 'category', label: 'Category' },
          { key: 'rating', type: 'number', label: 'Star rating', help: '0 = keep current.' },
          { key: 'image', type: 'image', label: 'Main photo in the app', help: 'Leave empty to use the Shopify photo.' },
        ],
      },
    ],
  },
  {
    key: 'coins',
    title: 'Rosier Coins',
    icon: 'database-outline',
    description: 'Earning rules, vouchers and everything on the Coins screen.',
    fields: [
      { key: 'earnPerRupee', type: 'number', label: 'Coins per ₹1', help: '0.05 = 5 coins for every ₹100.' },
      { key: 'welcomeBonus', type: 'number', label: 'Welcome coins' },
      { key: 'reviewBonus', type: 'number', label: 'Coins for a review' },
      { key: 'referralBonus', type: 'number', label: 'Coins for a referral' },
      { key: 'pendingDays', type: 'number', label: 'Days until coins unlock' },
      { key: 'minCartForVoucher', type: 'number', label: 'Minimum cart (₹) to use a voucher' },
      {
        key: 'vouchers',
        type: 'list',
        label: 'Vouchers',
        itemLabel: '₹{value} for {cost} coins',
        newItem: { id: '', value: 100, cost: 500, code: '', tint: 'brown' },
        fields: [
          { key: 'id', type: 'text', label: 'ID', help: 'Short unique ID, e.g. v100.' },
          { key: 'value', type: 'number', label: 'Discount (₹)' },
          { key: 'cost', type: 'number', label: 'Cost in coins' },
          { key: 'code', type: 'text', label: 'Shopify discount code', help: 'Must exist in Shopify → Discounts.' },
          {
            key: 'tint',
            type: 'select',
            label: 'Colour',
            options: ['copper', 'brown', 'green', 'deep'].map((v) => ({ value: v, label: v })),
          },
        ],
      },
      { key: 'referralMessage', type: 'textarea', label: 'Refer-a-friend share message' },
      {
        key: 'steps',
        type: 'list',
        label: 'How coins work (timeline)',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'promoTitle', type: 'textarea', label: 'Bottom banner title' },
      { key: 'promoBody', type: 'text', label: 'Bottom banner text' },
      { key: 'promoButton', type: 'text', label: 'Bottom banner button' },
      faq('FAQs'),
    ],
  },
  {
    key: 'benefits',
    title: 'Benefits Club',
    icon: 'crown-outline',
    description: 'The gold banner on home and the Benefits Club page.',
    fields: [
      { key: 'bannerTitle', type: 'text', label: 'Banner title' },
      { key: 'bannerSubtitle', type: 'text', label: 'Banner subtitle' },
      { key: 'bannerTagline', type: 'text', label: 'Banner tagline' },
      {
        key: 'bannerPerks',
        type: 'list',
        label: 'Banner perks (5 fit best)',
        itemLabel: '{label}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'label', type: 'textarea', label: 'Label' },
        ],
      },
      { key: 'pageTitle', type: 'text', label: 'Page title' },
      { key: 'pageSubtitle', type: 'text', label: 'Page subtitle' },
      { key: 'cardFooter', type: 'text', label: 'Text on the member card' },
      {
        key: 'perks',
        type: 'list',
        label: 'Page perks',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
      { key: 'plansTitle', type: 'text', label: 'Plans heading' },
      { key: 'popularPlanMonths', type: 'number', label: 'Plan marked POPULAR (months)' },
      { key: 'membershipHandle', type: 'product', label: 'Membership product' },
    ],
  },
  {
    key: 'reviews',
    title: 'Reviews',
    icon: 'star-outline',
    description: 'Customer reviews on the home screen.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Reviews',
        itemLabel: '{name} — {title}',
        newItem: { title: '', body: '', name: '', product: '', rating: 5, photo: '' },
        fields: [
          { key: 'title', type: 'text', label: 'Headline' },
          { key: 'body', type: 'textarea', label: 'Review' },
          { key: 'name', type: 'text', label: 'Customer name' },
          { key: 'product', type: 'text', label: 'Product name' },
          { key: 'rating', type: 'number', label: 'Stars (1–5)' },
          { key: 'photo', type: 'image', label: 'Customer photo (optional)' },
        ],
      },
    ],
  },
  {
    key: 'pillars',
    title: 'Rosier experience',
    icon: 'sprout-outline',
    description: 'The four pillars on home and Our Story.',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'subtitle', type: 'text', label: 'Subtitle' },
      {
        key: 'items',
        type: 'list',
        label: 'Pillars',
        itemLabel: '{title}',
        fields: [
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'text', label: 'Text' },
        ],
      },
    ],
  },
  {
    key: 'announcements',
    title: 'Notifications',
    icon: 'bell-outline',
    description: 'Messages that land in every user’s notification inbox in the app (with a red badge) the next time they open it.',
    fields: [
      {
        key: 'items',
        type: 'list',
        label: 'Messages',
        itemLabel: '{title}',
        newItem: { id: '', title: '', body: '', link: '' },
        autoId: true,
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
          { key: 'link', type: 'link', label: 'Opens when tapped (optional)', help: LINK_HELP },
        ],
      },
    ],
  },
  {
    key: 'about',
    title: 'Our Story',
    icon: 'book-open-page-variant-outline',
    fields: [
      { key: 'heroImage', type: 'image', label: 'Top image (optional)' },
      { key: 'headline', type: 'textarea', label: 'Headline' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      {
        key: 'blocks',
        type: 'list',
        label: 'Blocks',
        itemLabel: '{title}',
        newItem: { type: 'text', title: '', body: '', signature: '', image: '' },
        fields: [
          {
            key: 'type',
            type: 'select',
            label: 'Style',
            options: [
              { value: 'text', label: 'Heading + text' },
              { value: 'quote', label: 'Quote card' },
            ],
          },
          { key: 'title', type: 'text', label: 'Heading' },
          { key: 'body', type: 'textarea', label: 'Text', help: 'Leave a blank line between paragraphs.' },
          { key: 'signature', type: 'text', label: 'Signature', showIf: { type: ['quote'] } },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      { key: 'labReportsPath', type: 'text', label: 'Lab reports page on the website' },
      { key: 'websitePath', type: 'text', label: 'About page on the website' },
    ],
  },
  {
    key: 'blog',
    title: 'Blog',
    icon: 'newspaper-variant-outline',
    fields: [
      {
        key: 'articles',
        type: 'list',
        label: 'Articles',
        itemLabel: '{title}',
        autoId: true,
        newItem: { id: '', enabled: true, title: '', kicker: '', mins: 2, icon: 'leaf', colors: ['#F6D98C', '#C98A52'], image: '', product: '', body: '' },
        fields: [
          { key: 'enabled', type: 'boolean', label: 'Published' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'kicker', type: 'text', label: 'Tag (e.g. Tradition)' },
          { key: 'mins', type: 'number', label: 'Minutes to read' },
          { key: 'image', type: 'image', label: 'Cover image', help: 'If empty, the icon on a colour gradient is used.' },
          { key: 'icon', type: 'icon', label: 'Icon', help: ICON_HELP },
          { key: 'colors', type: 'colors', label: 'Cover gradient' },
          { key: 'body', type: 'textarea', label: 'Article', rows: 12, help: 'Leave a blank line between paragraphs.' },
          { key: 'product', type: 'product', label: '"Shop the product" button' },
        ],
      },
    ],
  },
  {
    key: 'gifting',
    title: 'Gifting',
    icon: 'gift-outline',
    fields: [
      { key: 'image', type: 'image', label: 'Header image (optional)' },
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'body', type: 'textarea', label: 'Text' },
      { key: 'buttonLabel', type: 'text', label: 'Button text' },
      { key: 'email', type: 'text', label: 'Enquiry email' },
      { key: 'subject', type: 'text', label: 'Email subject' },
      { key: 'category', type: 'category', label: 'Products shown' },
    ],
  },
  {
    key: 'help',
    title: 'Help & Support',
    icon: 'lifebuoy',
    fields: [
      { key: 'title', type: 'text', label: 'Title' },
      { key: 'intro', type: 'textarea', label: 'Intro' },
      { key: 'phone', type: 'text', label: 'Phone (with +91)' },
      { key: 'phoneLabel', type: 'text', label: 'Phone as shown' },
      { key: 'email', type: 'text', label: 'Email' },
      { key: 'contactPath', type: 'text', label: 'Contact page on the website' },
      faq('FAQs'),
      { key: 'company', type: 'text', label: 'Company name' },
      { key: 'address', type: 'textarea', label: 'Address' },
    ],
  },
  {
    key: 'search',
    title: 'Search',
    icon: 'magnify',
    fields: [{ key: 'popular', type: 'strings', label: 'Popular searches' }],
  },
  {
    key: 'general',
    title: 'App settings',
    icon: 'cog-outline',
    description: 'Logo, maintenance mode and forcing users to update.',
    fields: [
      { key: 'logo', type: 'image', label: 'Logo', help: 'Black logo on a transparent background — the app recolours it.' },
      { key: 'tagline', type: 'text', label: 'Tagline' },
      { key: 'footerNote', type: 'text', label: 'Home footer line' },
      {
        key: 'welcomeNotification',
        type: 'group',
        label: 'First notification new users get',
        fields: [
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'body', type: 'textarea', label: 'Message' },
        ],
      },
      {
        key: 'maintenance',
        type: 'group',
        label: 'Maintenance mode',
        fields: [
          { key: 'enabled', type: 'boolean', label: 'App is in maintenance (blocks the whole app)' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'image', type: 'image', label: 'Image (optional)' },
        ],
      },
      {
        key: 'update',
        type: 'group',
        label: 'App update prompt',
        fields: [
          { key: 'minVersion', type: 'text', label: 'Minimum app version', help: 'People on an older version see the update prompt. Current app version is 1.0.0.' },
          { key: 'force', type: 'boolean', label: 'Block the app until they update' },
          { key: 'title', type: 'text', label: 'Title' },
          { key: 'message', type: 'textarea', label: 'Message' },
          { key: 'androidUrl', type: 'text', label: 'Play Store link' },
          { key: 'iosUrl', type: 'text', label: 'App Store link' },
        ],
      },
    ],
  },
];

export const SECTION_KEYS = SCHEMA.map((s) => s.key);
